---
title: "WorkInProgress"
runtime: shiny_prerendered
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(EnvStats, quietly = TRUE, warn.conflicts = FALSE, verbose = FALSE) # For Pareto Distribution
```

```{r, echo=FALSE}

shinyUI(fluidPage(
  sidebarPanel(selectInput(inputId = "dist",
                label = "Distribution:",
                choices = c(Normal      = "rnorm",
                            Lognormal   = "rlnorm",
                            Uniform     = "runif",
                            Beta        = "rbeta",
                            Pareto      = "rparet"),
                selected = "rnorm"),
               
               conditionalPanel(condition = "input.dist == 'runif'",
                                sliderInput("range_unif", "Range", min = -100, max = 100, value = c(-5, 5))),
               
               conditionalPanel(condition = "input.dist == 'rbeta'",
                                sliderInput("alpha", "Alpha", min = 0, max = 1, step = 0.01, value = .5),
                                sliderInput("beta", "Beta", min = 0, max = 1, step = 0.01, value = .5)),
               
               conditionalPanel(condition = "input.dist == 'rnorm'",
                                sliderInput("mean_norm", "Mean", min = -5, max = 5, step = .1, value = 0),
                                sliderInput("std_norm", "Standard Deviation", min = 0.01, max = 5, step = 0.1, value = 1),
                                sliderInput("range_norm", "Range", min = -100, max = 100, value = c(-5, 5))),
               
               conditionalPanel(condition = "input.dist == 'rparet'",
                                sliderInput("location", "Location", min = 0.1, max = 10, step = .1, value = 1),
                                sliderInput("shape", "Shape", min = 0.1, max = 5, step = 0.1, value = 1),
                                sliderInput("range_paret", "Range", min = 0, max = 100, value = c(-5, 5))),
               
               conditionalPanel(condition = "input.dist == 'rlnorm'",
                                sliderInput("mean_lnorm", "Mean", min = -5, max = 5, step = .1, value = 0),
                                sliderInput("std_lnorm", "Standard Deviation", min = 0.01, max = 5, step = 0.1, value = 1),
                                sliderInput("range_lnorm", "Range", min = -100, max = 100, value = c(-5, 5)))),
  
  mainPanel(
    plotOutput("dPlot")
  )))
```

```{r, context="server"}
output$dPlot <- renderPlot({
  
  if (input$dist == 'rnorm'){ # Normal
    range <- seq(input$range_norm[1], input$range_norm[2], .1)
    plot(range,
         dnorm(range, mean = input$mean_norm, sd = input$std_norm), "l", col = "navyblue", ylab = "Density", xlab = "x", main = "Normal Distribution")
    
  } else if(input$dist == 'rlnorm'){ # Log Normal
    range <- seq(input$range_lnorm[1], input$range_lnorm[2], .1)
    plot(range,
         dlnorm(range, mean = input$mean_lnorm, sd = input$std_lnorm), "l", col = "navyblue", ylab = "Density", xlab = "x", main = "Lognormal Distribution")

  } else if(input$dist == 'runif'){
    range <- seq(input$range_unif[1], input$range_unif[2], .1)
    plot(range,
         dunif(range, min = input$range_unif[1], max = input$range_unif[2]), "l", col = "navyblue", ylab = "Density", xlab = "x", main = "Uniform Distribution")
    
  } else if(input$dist == 'rbeta') {
    range <- seq(0, 1, .01)
    plot(range,
         dbeta(range, shape1 = input$alpha, shape2 = input$beta), "l", col = "navyblue", ylab = "Density", xlab = "x", main = "Beta Distribution")
    
  } else if(input$dist == 'rparet'){
    range <- seq(input$range_paret[1], input$range_paret[2], .1)
    plot(range,
         dpareto(range, location = input$location, shape = input$shape), "l", col = "navyblue", ylab = "Density", xlab = "x", main = "Pareto Distribution")
  }
})
```

It's working ! :)
