app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(sb = 1)
app$setInputs(ib = -0.5)
app$setInputs(const = "2")
app$setInputs(s2 = 0.9)
app$setInputs(ex2 = 2)
app$setInputs(s2 = -1.2)
app$setInputs(const = "1")
app$setInputs(i2 = 0.2)
app$setInputs(i2 = 0.3)
app$snapshot()
app$setInputs(i2 = -2.4)
app$setInputs(ex2 = 3)
app$setInputs(const = "2")
app$setInputs(s2 = -0.7)
app$setInputs(s2 = -1.5)
app$setInputs(s2 = -1.3)
app$setInputs(s2 = -1.2)
app$setInputs(s2 = -1.1)
app$setInputs(s2 = -1)
app$setInputs(s2 = -1.1)
app$setInputs(s2 = -1.2)
app$setInputs(s2 = -0.6)
app$setInputs(s2 = -0.5)
app$setInputs(s2 = -0.4)
app$setInputs(s2 = -0.2)
app$snapshot()
