<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 IV Applications | Introduction to Econometrics with R</title>
  <meta name="description" content="SciencesPo UG Econometrics online textbook. Almost no Maths." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 IV Applications | Introduction to Econometrics with R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://scpoecon.github.io/ScPoEconometrics/" />
  
  <meta property="og:description" content="SciencesPo UG Econometrics online textbook. Almost no Maths." />
  <meta name="github-repo" content="ScPoEcon/ScPoEconometrics" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 IV Applications | Introduction to Econometrics with R" />
  
  <meta name="twitter:description" content="SciencesPo UG Econometrics online textbook. Almost no Maths." />
  

<meta name="author" content="Florian Oswald, Jean-Marc Robin and Vincent Viers" />


<meta name="date" content="2020-10-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.gif" type="image/x-icon" />
<link rel="prev" href="IV.html"/>
<link rel="next" href="panel-data.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.2.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-41584331-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-41584331-4');
</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ScPo 2nd Year Econometrics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Syllabus</a></li>
<li class="chapter" data-level="1" data-path="R-intro.html"><a href="R-intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to <code>R</code></a><ul>
<li class="chapter" data-level="1.1" data-path="R-intro.html"><a href="R-intro.html#getting-started"><i class="fa fa-check"></i><b>1.1</b> Getting Started</a></li>
<li class="chapter" data-level="1.2" data-path="R-intro.html"><a href="R-intro.html#starting-r-and-rstudio"><i class="fa fa-check"></i><b>1.2</b> Starting R and RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="R-intro.html"><a href="R-intro.html#basic-calculations"><i class="fa fa-check"></i><b>1.3</b> Basic Calculations</a></li>
<li class="chapter" data-level="1.4" data-path="R-intro.html"><a href="R-intro.html#getting-help"><i class="fa fa-check"></i><b>1.4</b> Getting Help</a></li>
<li class="chapter" data-level="1.5" data-path="R-intro.html"><a href="R-intro.html#installing-packages"><i class="fa fa-check"></i><b>1.5</b> Installing Packages</a></li>
<li class="chapter" data-level="1.6" data-path="R-intro.html"><a href="R-intro.html#code-output"><i class="fa fa-check"></i><b>1.6</b> <code>Code</code> vs Output in this Book</a></li>
<li class="chapter" data-level="1.7" data-path="R-intro.html"><a href="R-intro.html#install-package"><i class="fa fa-check"></i><b>1.7</b> <code>ScPoApps</code> Package</a></li>
<li class="chapter" data-level="1.8" data-path="R-intro.html"><a href="R-intro.html#data-types"><i class="fa fa-check"></i><b>1.8</b> Data Types</a></li>
<li class="chapter" data-level="1.9" data-path="R-intro.html"><a href="R-intro.html#data-structures"><i class="fa fa-check"></i><b>1.9</b> Data Structures</a></li>
<li class="chapter" data-level="1.10" data-path="R-intro.html"><a href="R-intro.html#dataframes"><i class="fa fa-check"></i><b>1.10</b> Data Frames</a></li>
<li class="chapter" data-level="1.11" data-path="R-intro.html"><a href="R-intro.html#programming-basics"><i class="fa fa-check"></i><b>1.11</b> Programming Basics</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="sum.html"><a href="sum.html"><i class="fa fa-check"></i><b>2</b> Working With Data</a><ul>
<li class="chapter" data-level="2.1" data-path="sum.html"><a href="sum.html#summary-statistics"><i class="fa fa-check"></i><b>2.1</b> Summary Statistics</a></li>
<li class="chapter" data-level="2.2" data-path="sum.html"><a href="sum.html#plotting"><i class="fa fa-check"></i><b>2.2</b> Plotting</a></li>
<li class="chapter" data-level="2.3" data-path="sum.html"><a href="sum.html#summarize-two"><i class="fa fa-check"></i><b>2.3</b> Summarizing Two Variables</a></li>
<li class="chapter" data-level="2.4" data-path="sum.html"><a href="sum.html#the-tidyverse"><i class="fa fa-check"></i><b>2.4</b> The <code>tidyverse</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="linreg.html"><a href="linreg.html"><i class="fa fa-check"></i><b>3</b> Linear Regression</a><ul>
<li class="chapter" data-level="3.1" data-path="linreg.html"><a href="linreg.html#how-are-x-and-y-related"><i class="fa fa-check"></i><b>3.1</b> How are <code>x</code> and <code>y</code> related?</a></li>
<li class="chapter" data-level="3.2" data-path="linreg.html"><a href="linreg.html#OLS"><i class="fa fa-check"></i><b>3.2</b> Ordinary Least Squares (OLS) Estimator</a></li>
<li class="chapter" data-level="3.3" data-path="linreg.html"><a href="linreg.html#pred-resids"><i class="fa fa-check"></i><b>3.3</b> Predictions and Residuals</a></li>
<li class="chapter" data-level="3.4" data-path="linreg.html"><a href="linreg.html#correlation-covariance-and-linearity"><i class="fa fa-check"></i><b>3.4</b> Correlation, Covariance and Linearity</a></li>
<li class="chapter" data-level="3.5" data-path="linreg.html"><a href="linreg.html#analysing-vary"><i class="fa fa-check"></i><b>3.5</b> Analysing <span class="math inline">\(Var(y)\)</span></a></li>
<li class="chapter" data-level="3.6" data-path="linreg.html"><a href="linreg.html#assessing-the-goodness-of-fit"><i class="fa fa-check"></i><b>3.6</b> Assessing the <em>Goodness of Fit</em></a></li>
<li class="chapter" data-level="3.7" data-path="linreg.html"><a href="linreg.html#an-example-a-log-wage-equation"><i class="fa fa-check"></i><b>3.7</b> An Example: A Log Wage Equation</a></li>
<li class="chapter" data-level="3.8" data-path="linreg.html"><a href="linreg.html#scaling-regressions"><i class="fa fa-check"></i><b>3.8</b> Scaling Regressions</a></li>
<li class="chapter" data-level="3.9" data-path="linreg.html"><a href="linreg.html#a-particular-rescaling-the-log-transform"><i class="fa fa-check"></i><b>3.9</b> A Particular Rescaling: The <span class="math inline">\(\log\)</span> Transform</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="multiple-reg.html"><a href="multiple-reg.html"><i class="fa fa-check"></i><b>4</b> Multiple Regression</a><ul>
<li class="chapter" data-level="4.1" data-path="multiple-reg.html"><a href="multiple-reg.html#ceteris"><i class="fa fa-check"></i><b>4.1</b> All Else Equal</a></li>
<li class="chapter" data-level="4.2" data-path="multiple-reg.html"><a href="multiple-reg.html#multicol"><i class="fa fa-check"></i><b>4.2</b> Multicolinearity</a></li>
<li class="chapter" data-level="4.3" data-path="multiple-reg.html"><a href="multiple-reg.html#log-wage-equation"><i class="fa fa-check"></i><b>4.3</b> Log Wage Equation</a></li>
<li class="chapter" data-level="4.4" data-path="multiple-reg.html"><a href="multiple-reg.html#make-preds"><i class="fa fa-check"></i><b>4.4</b> How To Make Predictions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="categorical-vars.html"><a href="categorical-vars.html"><i class="fa fa-check"></i><b>5</b> Categorial Variables</a><ul>
<li class="chapter" data-level="5.1" data-path="categorical-vars.html"><a href="categorical-vars.html#the-binary-regressor-case"><i class="fa fa-check"></i><b>5.1</b> The Binary Regressor Case</a></li>
<li class="chapter" data-level="5.2" data-path="categorical-vars.html"><a href="categorical-vars.html#dummy-and-continuous-variables"><i class="fa fa-check"></i><b>5.2</b> Dummy and Continuous Variables</a></li>
<li class="chapter" data-level="5.3" data-path="categorical-vars.html"><a href="categorical-vars.html#categorical-variables-in-r-factor"><i class="fa fa-check"></i><b>5.3</b> Categorical Variables in <code>R</code>: <code>factor</code></a></li>
<li class="chapter" data-level="5.4" data-path="categorical-vars.html"><a href="categorical-vars.html#interactions"><i class="fa fa-check"></i><b>5.4</b> Interactions</a></li>
<li class="chapter" data-level="5.5" data-path="categorical-vars.html"><a href="categorical-vars.html#unobserved-individual-heterogeneity"><i class="fa fa-check"></i><b>5.5</b> (Unobserved) Individual Heterogeneity</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="std-errors.html"><a href="std-errors.html"><i class="fa fa-check"></i><b>6</b> Regression Inference</a><ul>
<li class="chapter" data-level="6.1" data-path="std-errors.html"><a href="std-errors.html#sampling"><i class="fa fa-check"></i><b>6.1</b> Sampling</a></li>
<li class="chapter" data-level="6.2" data-path="std-errors.html"><a href="std-errors.html#taking-eleven-samples-from-the-population"><i class="fa fa-check"></i><b>6.2</b> Taking Eleven Samples From The Population</a></li>
<li class="chapter" data-level="6.3" data-path="std-errors.html"><a href="std-errors.html#handover-to-moderndive"><i class="fa fa-check"></i><b>6.3</b> Handover to <code>Moderndive</code></a></li>
<li class="chapter" data-level="6.4" data-path="std-errors.html"><a href="std-errors.html#uncertainty-in-regression-estimates"><i class="fa fa-check"></i><b>6.4</b> Uncertainty in Regression Estimates</a></li>
<li class="chapter" data-level="6.5" data-path="std-errors.html"><a href="std-errors.html#what-is-true-what-are-statistical-models"><i class="fa fa-check"></i><b>6.5</b> What is <em>true</em>? What are Statistical Models?</a></li>
<li class="chapter" data-level="6.6" data-path="std-errors.html"><a href="std-errors.html#class-reg"><i class="fa fa-check"></i><b>6.6</b> The Classical Regression Model (CRM)</a></li>
<li class="chapter" data-level="6.7" data-path="std-errors.html"><a href="std-errors.html#se-theory"><i class="fa fa-check"></i><b>6.7</b> Standard Errors in Theory</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="causality.html"><a href="causality.html"><i class="fa fa-check"></i><b>7</b> Causality</a><ul>
<li class="chapter" data-level="7.1" data-path="causality.html"><a href="causality.html#dags"><i class="fa fa-check"></i><b>7.1</b> Directed Acyclical Graphs (DAG)</a></li>
<li class="chapter" data-level="7.2" data-path="causality.html"><a href="causality.html#smoking-in-a-dag"><i class="fa fa-check"></i><b>7.2</b> Smoking in a DAG</a></li>
<li class="chapter" data-level="7.3" data-path="causality.html"><a href="causality.html#rct"><i class="fa fa-check"></i><b>7.3</b> Randomized Control Trials (RCT) Primer</a></li>
<li class="chapter" data-level="7.4" data-path="causality.html"><a href="causality.html#rubin"><i class="fa fa-check"></i><b>7.4</b> The Potential Outcomes Model</a></li>
<li class="chapter" data-level="7.5" data-path="causality.html"><a href="causality.html#omitted-variable-bias-and-dags"><i class="fa fa-check"></i><b>7.5</b> Omitted Variable Bias and DAGs</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="STAR.html"><a href="STAR.html"><i class="fa fa-check"></i><b>8</b> STAR Experiment</a><ul>
<li class="chapter" data-level="8.1" data-path="STAR.html"><a href="STAR.html#the-star-experiment"><i class="fa fa-check"></i><b>8.1</b> The STAR Experiment</a></li>
<li class="chapter" data-level="8.2" data-path="STAR.html"><a href="STAR.html#po-as-regression"><i class="fa fa-check"></i><b>8.2</b> PO as Regression</a></li>
<li class="chapter" data-level="8.3" data-path="STAR.html"><a href="STAR.html#implementing-star"><i class="fa fa-check"></i><b>8.3</b> Implementing STAR</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="RDD.html"><a href="RDD.html"><i class="fa fa-check"></i><b>9</b> Regression Discontinuity Design</a><ul>
<li class="chapter" data-level="9.1" data-path="RDD.html"><a href="RDD.html#rdd-setup"><i class="fa fa-check"></i><b>9.1</b> RDD Setup</a></li>
<li class="chapter" data-level="9.2" data-path="RDD.html"><a href="RDD.html#clicking-on-heavens-door"><i class="fa fa-check"></i><b>9.2</b> Clicking on Heaven’s Door</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="IV.html"><a href="IV.html"><i class="fa fa-check"></i><b>10</b> Instrumental Variables (IV)</a><ul>
<li class="chapter" data-level="10.1" data-path="IV.html"><a href="IV.html#john-snow-and-the-london-cholera-epidemic"><i class="fa fa-check"></i><b>10.1</b> John Snow and the London Cholera Epidemic</a></li>
<li class="chapter" data-level="10.2" data-path="IV.html"><a href="IV.html#defining-the-iv-estimator"><i class="fa fa-check"></i><b>10.2</b> Defining the IV Estimator</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="iv-applications.html"><a href="iv-applications.html"><i class="fa fa-check"></i><b>11</b> IV Applications</a><ul>
<li class="chapter" data-level="11.1" data-path="iv-applications.html"><a href="iv-applications.html#ability-bias"><i class="fa fa-check"></i><b>11.1</b> Ability Bias</a></li>
<li class="chapter" data-level="11.2" data-path="iv-applications.html"><a href="iv-applications.html#birthdate-is-as-good-as-random"><i class="fa fa-check"></i><b>11.2</b> Birthdate is as good as Random</a></li>
<li class="chapter" data-level="11.3" data-path="iv-applications.html"><a href="iv-applications.html#IV-mech"><i class="fa fa-check"></i><b>11.3</b> IV Mechanics</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="panel-data.html"><a href="panel-data.html"><i class="fa fa-check"></i><b>12</b> Panel Data</a><ul>
<li class="chapter" data-level="12.1" data-path="panel-data.html"><a href="panel-data.html#crime-rate-vs-probability-of-arrest"><i class="fa fa-check"></i><b>12.1</b> Crime Rate vs Probability of Arrest</a></li>
<li class="chapter" data-level="12.2" data-path="panel-data.html"><a href="panel-data.html#panel-data-estimation-with-r"><i class="fa fa-check"></i><b>12.2</b> Panel Data Estimation with <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="binary.html"><a href="binary.html"><i class="fa fa-check"></i><b>13</b> Binary Outcomes</a><ul>
<li class="chapter" data-level="13.1" data-path="binary.html"><a href="binary.html#the-linear-probability-model"><i class="fa fa-check"></i><b>13.1</b> The Linear Probability Model</a></li>
<li class="chapter" data-level="13.2" data-path="binary.html"><a href="binary.html#nonlinear-binary-response-models"><i class="fa fa-check"></i><b>13.2</b> Nonlinear Binary Response Models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="iv-applications" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> IV Applications</h1>
<p>An important term in economics are the <em>returns to schooling</em>, by which we mean the causal effect of education on later earnings. If you think about it, it’s a crucial question for every single student (like yourself), if not even more so for a policy maker who needs to decide where to allocate budget spending on (education or other things?).</p>
<p>One very famous and early study to estimate those returns to schooling was proposed by Jacob Mincer, and an equation of this kind was henceforth known as the <em>Mincer Equation</em> (we have encountered this equation before as a running example in chapter <a href="linreg.html#linreg">3</a>). He measured <span class="math inline">\(\log Y_i\)</span>, annual earnings for man <span class="math inline">\(i\)</span>, <span class="math inline">\(S_i\)</span> his schooling (years spent studying), and <span class="math inline">\(X_i\)</span> his (potential) work experience (age minus years of schooling minus 6). The model can be drawn like this:</p>
<div class="figure" style="text-align: center"><span id="fig:mincer"></span>
<img src="ScPoEconometrics_files/figure-html/mincer-1.png" alt="Jacob Mincer's model" width="672" />
<p class="caption">
Figure 11.1: Jacob Mincer’s model
</p>
</div>
<p>Hourly earnings are assumed to be affected by experience and schooling <em>only</em>. In terms of an equation,</p>
<p><span class="math display" id="eq:mincer">\[\begin{equation}
\log Y_i = \alpha + \rho S_i + \beta_1 X_i + \beta_2 X_i^2 + e_i  \tag{11.1}
\end{equation}\]</span></p>
<p>His results implied an estimate for <span class="math inline">\(\rho\)</span> of about 0.11, or an 11% earnings advantage for each additional year of education, given a certain level of experience. Notice that in the DAG in figure <a href="iv-applications.html#fig:mincer">11.1</a>, we explicitly drew other unobserved factors <span class="math inline">\(e\)</span> with <em>only</em> have an arrow directly into <span class="math inline">\(y\)</span>. But is that a good model? Well, why would it not be?</p>
<div id="ability-bias" class="section level2">
<h2><span class="header-section-number">11.1</span> Ability Bias</h2>
<p>The model in <a href="iv-applications.html#eq:mincer">(11.1)</a> compares earnings of men with certain schooling and work experience. The question to ask, if given those two controls, all else is equal? For a given value of <span class="math inline">\(X\)</span>, are there more diligent and able workers out there? Do family connections vary across people with the same <span class="math inline">\(X\)</span>? It seems quite likely that we’d answer yes. Well, then, all else is <em>not</em> equal, and we are in trouble. Because, again, our crucial identifying assumption for the linear model is violated, as</p>
<p><span class="math display">\[E[e_i | S_i, X_i] \neq 0.\]</span></p>
<p>Our concern can be formalized by explicitly introducing <em>ability</em> <span class="math inline">\(A\)</span> as an (unobserved) factor into our model. That means we have now <em>two</em> unobservables - of course we can’t tell them apart, so let’s write them as a new unobservable factor <span class="math inline">\(u_i = e_i + A_i\)</span>. Then we could visualize this new model as follows:</p>
<div class="figure" style="text-align: center"><span id="fig:mincer2"></span>
<img src="ScPoEconometrics_files/figure-html/mincer2-1.png" alt="Jacob Mincer's model with unobserved ability $A$. Given it's *unobserved* it is lumped together with all other unobservable factors in $e$, and we've called it $u = e + A$." width="672" />
<p class="caption">
Figure 11.2: Jacob Mincer’s model with unobserved ability <span class="math inline">\(A\)</span>. Given it’s <em>unobserved</em> it is lumped together with all other unobservable factors in <span class="math inline">\(e\)</span>, and we’ve called it <span class="math inline">\(u = e + A\)</span>.
</p>
</div>
<p>In figure <a href="iv-applications.html#fig:mincer2">11.2</a>, the unobserved factor <span class="math inline">\(A\)</span> influences <em>both</em> years of schooling and earnings on the labor market. For example, if we think for <span class="math inline">\(A\)</span> as something like <em>intelligence</em>, it might be that more intelligent students find it less painful to attend school (it’s less costly for them in terms of effort), so they get more education, and also they earn higher wages because their intelligence is rewarded in the labor market. The same works if <span class="math inline">\(A\)</span> is related to family type and network. Suppose a family with high socio-economic status is also well connected. Then high <span class="math inline">\(A\)</span> could mean that the parents of <span class="math inline">\(i\)</span> know that education is a good signalling device (so they force <span class="math inline">\(i\)</span> to go to university, say), while at the same time their good network means that high <span class="math inline">\(A\)</span> will mean a good job and hence earnings. We would write in terms of an equation</p>
<p><span class="math display" id="eq:ability">\[\begin{equation}
\log Y_i = \alpha + \rho S_i + \beta_1 X_i + \beta_2 X_i^2 + \underbrace{u_i}_{A_i + e_i}  \tag{11.2}
\end{equation}\]</span></p>
<p>Sometimes these considerations do not matter greatly, and the (biased) OLS estimate is close the causal IV estimate. But in other cases, we might be very far from the truth with OLS, even inferring the wrong sign of an effect. Let’s look at an example!</p>
</div>
<div id="birthdate-is-as-good-as-random" class="section level2">
<h2><span class="header-section-number">11.2</span> Birthdate is as good as Random</h2>
<p>In an influential study, <span class="citation">Angrist and Krueger (<a href="#ref-angristkrueger" role="doc-biblioref">1991</a>)</span> address the above issues related to the ability bias in Mincer’s equation by constructing an IV which encodes the birth date of a given student. The idea is that given certain features of the school system, children born shortly after a certain cutoff date will start school a year later than their peers who are a bit older than they are.</p>
<p>For example, suppose it is mandated that all children who reach the age of 6 by 31st of december 2021 are required to enroll in the first grade of school in september 2021. Then someone born in September 2015 (i.e. 6 years prior) will be 5 years and 3/4 by the time they start school, while someone born on the 1st of January 2016 will be 6 and 3/4 years when <em>they</em> enter school in september 2022. Furthermore, the legal dropout age in the US is 16, so by the time those pupils may decide to stop school, they have been exposed to different amounts of schooling. All of this means that an IV defined by <em>quarter of birth of person <span class="math inline">\(i\)</span></em> will affect the outcome <em>earnings</em> through it’s effect on more schooling - keeping other factors (in particular <span class="math inline">\(A\)</span>!) constant across values of the IV. What’s the implication for our model?</p>
<div class="figure" style="text-align: center"><span id="fig:ak-mod"></span>
<img src="ScPoEconometrics_files/figure-html/ak-mod-1.png" alt="Angrist and Krueger's IV in to tackle ability bias." width="672" />
<p class="caption">
Figure 11.3: Angrist and Krueger’s IV in to tackle ability bias.
</p>
</div>
<p>In the DAG for <span class="citation">Angrist and Krueger (<a href="#ref-angristkrueger" role="doc-biblioref">1991</a>)</span>’s model in <a href="iv-applications.html#fig:ak-mod">11.3</a> we see that the IV directly impacts the endogenous explanatory variable <span class="math inline">\(s\)</span>, but is itself independent of <span class="math inline">\(u\)</span> - we argued that <span class="math inline">\(A\)</span> is equally distributed across different birth quarters <span class="math inline">\(z\)</span> (birth date is almost random). Let us now formulate the following two-stage procedure:</p>
<ol style="list-style-type: decimal">
<li>We estimate a <strong>first stage model</strong> which uses only exogenous variables (like <span class="math inline">\(z\)</span>) to explain our endgenous regressor <span class="math inline">\(s\)</span>.</li>
<li>We then use the first stage model to <em>predict</em> values of <span class="math inline">\(s\)</span> in what is called the <strong>second stage</strong> or the <strong>reduced form</strong> model.<a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a> Performing this procedure is supposed to take out any impact of <span class="math inline">\(A\)</span> in the correlation we observe in our data between <span class="math inline">\(s\)</span> and <span class="math inline">\(y\)</span>.</li>
</ol>
<p>This estimation technique is called the <strong>Two stage least squares</strong> estimator, or 2SLS for short. The great virtue is that in the first stage we could have any number of exogenous variables helping to predict our exogenous <span class="math inline">\(s\)</span> (here we have just one - quarter of birth.) In terms of equations, we could write the following:</p>
<p><span class="math display" id="eq:2SLS2" id="eq:2SLS1">\[\begin{align}
\text{1. Stage: }s_i &amp;= \alpha_0 + \alpha_1 z_i + \eta_i \tag{11.3}\\ 
\text{2. Stage: }y_i &amp;= \beta_0 + \beta_1 \hat{s}_i + u_i \tag{11.4}
\end{align}\]</span></p>
<p>where the <span class="math inline">\(\hat{s}_i\)</span> means to insert the <em>predicted</em> value from the first stage for <span class="math inline">\(i\)</span>’s observed <span class="math inline">\(s_i\)</span> in the second stage regression. We can write down the conditions for a valid IV <span class="math inline">\(z\)</span> in this context:</p>
<div class="warningl">
<p>
<strong>Conditions for a valid Instrument in this simple 2SLS setup</strong>:
</p>
<ol style="list-style-type: decimal">
<li>
Relevance of the IV: <span class="math inline"><span class="math inline">\(\alpha_1 \neq 0\)</span></span>
</li>
<li>
Independence (IV assignment as good as random): <span class="math inline"><span class="math inline">\(E[\eta | z] = 0\)</span></span>
</li>
<li>
Exogeneity (our exclusion restriction): <span class="math inline"><span class="math inline">\(E[u | z] = 0\)</span></span>
</li>
</ol>
</div>
<div id="data-on-birth-quarter-and-wages" class="section level3">
<h3><span class="header-section-number">11.2.1</span> Data on birth quarter and wages</h3>
<p>Let’s load the data and look at a quick summary<a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a>:</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="iv-applications.html#cb388-1"></a><span class="kw">data</span>(<span class="st">&quot;ak91&quot;</span>, <span class="dt">package =</span> <span class="st">&quot;masteringmetrics&quot;</span>)</span>
<span id="cb388-2"><a href="iv-applications.html#cb388-2"></a><span class="co"># library(modelsummary) # loaded already for me</span></span>
<span id="cb388-3"><a href="iv-applications.html#cb388-3"></a><span class="kw">datasummary_skim</span>(<span class="kw">data.frame</span>(ak91),<span class="dt">histogram =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
P0
</th>
<th style="text-align:right;">
P25
</th>
<th style="text-align:right;">
P50
</th>
<th style="text-align:right;">
P75
</th>
<th style="text-align:right;">
P100
</th>
<th style="text-align:right;">
Histogram
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
lnw
</td>
<td style="text-align:right;">
5.9
</td>
<td style="text-align:right;">
0.7
</td>
<td style="text-align:right;">
-2.3
</td>
<td style="text-align:right;">
5.6
</td>
<td style="text-align:right;">
6.0
</td>
<td style="text-align:right;">
6.3
</td>
<td style="text-align:right;">
10.5
</td>
<td style="text-align:right;">
▁▇▁
</td>
</tr>
<tr>
<td style="text-align:left;">
s
</td>
<td style="text-align:right;">
12.8
</td>
<td style="text-align:right;">
3.3
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
15.0
</td>
<td style="text-align:right;">
20.0
</td>
<td style="text-align:right;">
▁▂▇▂▂▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
yob
</td>
<td style="text-align:right;">
1934.6
</td>
<td style="text-align:right;">
2.9
</td>
<td style="text-align:right;">
1930.0
</td>
<td style="text-align:right;">
1932.0
</td>
<td style="text-align:right;">
1935.0
</td>
<td style="text-align:right;">
1937.0
</td>
<td style="text-align:right;">
1939.0
</td>
<td style="text-align:right;">
▇▆▆▆▆▆▆▇▇▇
</td>
</tr>
<tr>
<td style="text-align:left;">
qob
</td>
<td style="text-align:right;">
2.5
</td>
<td style="text-align:right;">
1.1
</td>
<td style="text-align:right;">
1.0
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
3.0
</td>
<td style="text-align:right;">
4.0
</td>
<td style="text-align:right;">
▇▆▇▇
</td>
</tr>
<tr>
<td style="text-align:left;">
sob
</td>
<td style="text-align:right;">
30.7
</td>
<td style="text-align:right;">
14.2
</td>
<td style="text-align:right;">
1.0
</td>
<td style="text-align:right;">
19.0
</td>
<td style="text-align:right;">
34.0
</td>
<td style="text-align:right;">
42.0
</td>
<td style="text-align:right;">
56.0
</td>
<td style="text-align:right;">
▃▁▃▄▅▃▇▅▃▃
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
45.0
</td>
<td style="text-align:right;">
2.9
</td>
<td style="text-align:right;">
40.2
</td>
<td style="text-align:right;">
42.5
</td>
<td style="text-align:right;">
45.0
</td>
<td style="text-align:right;">
47.5
</td>
<td style="text-align:right;">
50.0
</td>
<td style="text-align:right;">
▇▇▇▆▆▆▆▆▆▇
</td>
</tr>
</tbody>
</table>
<p>We convert quarter of birth to a factor:</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="iv-applications.html#cb389-1"></a>ak91 &lt;-<span class="st"> </span><span class="kw">mutate</span>(ak91,</span>
<span id="cb389-2"><a href="iv-applications.html#cb389-2"></a>               <span class="dt">qob_fct =</span> <span class="kw">factor</span>(qob),</span>
<span id="cb389-3"><a href="iv-applications.html#cb389-3"></a>               <span class="dt">q4 =</span> <span class="kw">as.integer</span>(qob <span class="op">==</span><span class="st"> &quot;4&quot;</span>),</span>
<span id="cb389-4"><a href="iv-applications.html#cb389-4"></a>               <span class="dt">yob_fct =</span> <span class="kw">factor</span>(yob))</span>
<span id="cb389-5"><a href="iv-applications.html#cb389-5"></a><span class="co"># get mean wage by year/quarter</span></span>
<span id="cb389-6"><a href="iv-applications.html#cb389-6"></a>ak91_age &lt;-<span class="st"> </span>ak91 <span class="op">%&gt;%</span></span>
<span id="cb389-7"><a href="iv-applications.html#cb389-7"></a><span class="st">  </span><span class="kw">group_by</span>(qob, yob) <span class="op">%&gt;%</span></span>
<span id="cb389-8"><a href="iv-applications.html#cb389-8"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">lnw =</span> <span class="kw">mean</span>(lnw), <span class="dt">s =</span> <span class="kw">mean</span>(s)) <span class="op">%&gt;%</span></span>
<span id="cb389-9"><a href="iv-applications.html#cb389-9"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">q4 =</span> (qob <span class="op">==</span><span class="st"> </span><span class="dv">4</span>))</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;qob&#39; (override with `.groups` argument)</code></pre>
<p>Let’s reproduce their first figure now on education as a function of quarter of birth!</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="iv-applications.html#cb391-1"></a><span class="kw">ggplot</span>(ak91_age, <span class="kw">aes</span>(<span class="dt">x =</span> yob <span class="op">+</span><span class="st"> </span>(qob <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span><span class="dv">4</span>, <span class="dt">y =</span> s )) <span class="op">+</span></span>
<span id="cb391-2"><a href="iv-applications.html#cb391-2"></a><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb391-3"><a href="iv-applications.html#cb391-3"></a><span class="st">  </span><span class="kw">geom_label</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">label =</span> qob, <span class="dt">color =</span> q4)) <span class="op">+</span></span>
<span id="cb391-4"><a href="iv-applications.html#cb391-4"></a><span class="st">  </span><span class="kw">guides</span>(<span class="dt">label =</span> <span class="ot">FALSE</span>, <span class="dt">color =</span> <span class="ot">FALSE</span>) <span class="op">+</span></span>
<span id="cb391-5"><a href="iv-applications.html#cb391-5"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="st">&quot;Year of birth&quot;</span>, <span class="dt">breaks =</span> <span class="dv">1930</span><span class="op">:</span><span class="dv">1940</span>) <span class="op">+</span></span>
<span id="cb391-6"><a href="iv-applications.html#cb391-6"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="st">&quot;Years of Education&quot;</span>, <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="fl">12.2</span>, <span class="fl">13.2</span>, <span class="dt">by =</span> <span class="fl">0.2</span>),</span>
<span id="cb391-7"><a href="iv-applications.html#cb391-7"></a>                     <span class="dt">limits =</span> <span class="kw">c</span>(<span class="fl">12.2</span>, <span class="fl">13.2</span>)) <span class="op">+</span></span>
<span id="cb391-8"><a href="iv-applications.html#cb391-8"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:ak91-age"></span>
<img src="ScPoEconometrics_files/figure-html/ak91-age-1.png" alt="Reproducing figure 1 from @angristkruegerIV" width="672" />
<p class="caption">
Figure 11.4: Reproducing figure 1 from <span class="citation">Angrist and Krueger (<a href="#ref-angristkruegerIV" role="doc-biblioref">2001</a>)</span>
</p>
</div>
<p>In figure <a href="iv-applications.html#fig:ak91-age">11.4</a> we see first that there was a trend in getting more and more education as time passed. Secondly, and more importantly here, is that for almost all birth years in the sample, the group born in quarter 4 has the highest value for years of education! So what we said above about the instutional rules of school attendance in the US seems to be born out in this dataset. What about earnings for those groups?</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="iv-applications.html#cb392-1"></a><span class="kw">ggplot</span>(ak91_age, <span class="kw">aes</span>(<span class="dt">x =</span> yob <span class="op">+</span><span class="st"> </span>(qob <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span><span class="dv">4</span>, <span class="dt">y =</span> lnw)) <span class="op">+</span></span>
<span id="cb392-2"><a href="iv-applications.html#cb392-2"></a><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></span>
<span id="cb392-3"><a href="iv-applications.html#cb392-3"></a><span class="st">  </span><span class="kw">geom_label</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">label =</span> qob, <span class="dt">color =</span> q4)) <span class="op">+</span></span>
<span id="cb392-4"><a href="iv-applications.html#cb392-4"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="st">&quot;Year of birth&quot;</span>, <span class="dt">breaks =</span> <span class="dv">1930</span><span class="op">:</span><span class="dv">1940</span>) <span class="op">+</span></span>
<span id="cb392-5"><a href="iv-applications.html#cb392-5"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="st">&quot;Log weekly wages&quot;</span>) <span class="op">+</span></span>
<span id="cb392-6"><a href="iv-applications.html#cb392-6"></a><span class="st">  </span><span class="kw">guides</span>(<span class="dt">label =</span> <span class="ot">FALSE</span>, <span class="dt">color =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st">  </span></span>
<span id="cb392-7"><a href="iv-applications.html#cb392-7"></a><span class="st">  </span><span class="kw">theme_bw</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:ak91-wage"></span>
<img src="ScPoEconometrics_files/figure-html/ak91-wage-1.png" alt="Reproducing figure 2 from @angristkruegerIV" width="672" />
<p class="caption">
Figure 11.5: Reproducing figure 2 from <span class="citation">Angrist and Krueger (<a href="#ref-angristkruegerIV" role="doc-biblioref">2001</a>)</span>
</p>
</div>
<p>Figure <a href="iv-applications.html#fig:ak91-wage">11.5</a> does not show a long running trend in earnings, so on average we’d say an hourly wage of 5 Dollars 90 per week. But, again, the group born in the fourth quarter seems special: In many cases they earn the highest or close to highest wage if compared to the other 3 groups in their birthyear. So, there really seems to be a relationship between quarter of birth and later in life earnings! Let us now construct an IV estimator, which will allow us to relate the sawtooth pattern in figure <a href="iv-applications.html#fig:ak91-age">11.4</a> to the one in <a href="iv-applications.html#fig:ak91-wage">11.5</a>. We will start out with using just <em>born in fourth quarter</em> as our IV.</p>
</div>
<div id="running-iv-estimation-in-r" class="section level3">
<h3><span class="header-section-number">11.2.2</span> Running IV estimation in <code>R</code></h3>
<p>There are several possibilities to run IV estimation in <code>R</code>. We will use the <code>iv_robust</code> function from the <code>estimatr</code> package.<a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a> Let’s estimate a simple OLS version (subject to ability bias), the first stage and second stages, and the final 2SLS estimate:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="iv-applications.html#cb393-1"></a>mod                  &lt;-<span class="st"> </span><span class="kw">list</span>()</span>
<span id="cb393-2"><a href="iv-applications.html#cb393-2"></a>mod<span class="op">$</span>ols              &lt;-<span class="st"> </span><span class="kw">lm</span>(lnw <span class="op">~</span><span class="st"> </span>s, <span class="dt">data =</span> ak91)</span>
<span id="cb393-3"><a href="iv-applications.html#cb393-3"></a>mod[[<span class="st">&quot;first stage&quot;</span>]] &lt;-<span class="st"> </span><span class="kw">lm</span>(s <span class="op">~</span><span class="st"> </span>q4, <span class="dt">data =</span> ak91)  <span class="co"># IV: born in q4 is TRUE?</span></span>
<span id="cb393-4"><a href="iv-applications.html#cb393-4"></a>ak91<span class="op">$</span>shat            &lt;-<span class="st"> </span><span class="kw">predict</span>(mod[[<span class="st">&quot;first stage&quot;</span>]])  </span>
<span id="cb393-5"><a href="iv-applications.html#cb393-5"></a>mod[[<span class="st">&quot;second stage&quot;</span>]] &lt;-<span class="st"> </span><span class="kw">lm</span>(lnw <span class="op">~</span><span class="st"> </span>shat, <span class="dt">data =</span> ak91)</span>
<span id="cb393-6"><a href="iv-applications.html#cb393-6"></a>mod<span class="op">$</span><span class="st">`</span><span class="dt">2SLS</span><span class="st">`</span>            &lt;-<span class="st"> </span>estimatr<span class="op">::</span><span class="kw">iv_robust</span>(lnw <span class="op">~</span><span class="st"> </span>s <span class="op">|</span><span class="st"> </span>q4, <span class="dt">data =</span> ak91 ) <span class="co"># IV: born in q4 is TRUE?</span></span></code></pre></div>
<p>Let’s look at those models next to each other in table <a href="iv-applications.html#tab:ms1">11.1</a>:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ms1">Table 11.1: </span>OLS, first and sceond stages as well as 2SLS estimates for Angrist and Krueger (1991)
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
ols
</th>
<th style="text-align:left;">
first stage
</th>
<th style="text-align:left;">
second stage
</th>
<th style="text-align:left;">
2SLS
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:left;">
4.995***
</td>
<td style="text-align:left;">
12.747***
</td>
<td style="text-align:left;">
4.955***
</td>
<td style="text-align:left;">
4.955***
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.004)
</td>
<td style="text-align:left;">
(0.007)
</td>
<td style="text-align:left;">
(0.381)
</td>
<td style="text-align:left;">
(0.358)
</td>
</tr>
<tr>
<td style="text-align:left;">
s
</td>
<td style="text-align:left;">
0.071***
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
0.074***
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.000)
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.028)
</td>
</tr>
<tr>
<td style="text-align:left;">
q4
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
0.092***
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.013)
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
shat
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
0.074**
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.030)
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:left;">
43782.556
</td>
<td style="text-align:left;">
48.095
</td>
<td style="text-align:left;">
6.146
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border:0;" colspan="100%">
<sup></sup> * p &lt; 0.1, ** p &lt; 0.05, *** p &lt; 0.01
</td>
</tr>
</tfoot>
</table>
<p>Table <a href="iv-applications.html#tab:ms1">11.1</a> contains a lot of information, so let’s go column-wise:</p>
<ol style="list-style-type: decimal">
<li>The column labelled <strong>ols</strong> is the basic earnings equation similar to Mincer’s model (without experience). We are worried about bias from the omitted variable <em>ability</em>, but we note that here we estimate a 7% higher wage for each additional year of schooling.</li>
<li>The next column is the first stage, i.e. the estimates for <span class="math inline">\(\alpha\)</span> in equation <a href="iv-applications.html#eq:2SLS1">(11.3)</a>. Remember we require that <span class="math inline">\(\alpha_1 \neq 0\)</span>. That seems to be the case here (p-value very small).</li>
<li>Then we run the second stage model with the predicted values <span class="math inline">\(\hat{s}\)</span> from the first stage, i.e. we estimate the <span class="math inline">\(\beta\)</span>s in <a href="iv-applications.html#eq:2SLS2">(11.4)</a>. You should compare <code>s</code> and <code>shat</code> in the first and third column.</li>
<li>Finally, we perform first and second stag e estimation in one go (you would usually go down this route directly) with 2SLS. You should compare <code>shat</code> from the second stage with the <code>s</code> estimate from the 2SLS model! The reason you should always go directly to something like <code>iv_robust</code> is that this procedure handles computation of standard errors correctly. In other words, the displayed standard error in the second stage for <code>shat</code> (0.03) is not taking into account that we estimated <code>shat</code> itself in a previous step - <code>iv_robust</code> does (note the small difference to 0.028).</li>
</ol>
</div>
<div id="additional-control-variables" class="section level3">
<h3><span class="header-section-number">11.2.3</span> Additional Control Variables</h3>
<p>We saw in figure <a href="iv-applications.html#fig:ak91-age">11.4</a> that there is a clear time trend in years of schooling. There are also business-cycle fluctuations in earnings, even if we were not able to see them from the graph above. It is probably a good idea to control for calendar year in order to guard against any time effects in our results. Also, we can use more than one IV! Here is how:</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="iv-applications.html#cb394-1"></a>mod<span class="op">$</span>ols_yr  &lt;-<span class="st"> </span><span class="kw">update</span>(mod<span class="op">$</span>ols, . <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>yob_fct)  <span class="co"># just update previous model</span></span>
<span id="cb394-2"><a href="iv-applications.html#cb394-2"></a>mod[[<span class="st">&quot;2SLS_yr&quot;</span>]] &lt;-<span class="st"> </span>estimatr<span class="op">::</span><span class="kw">iv_robust</span>(lnw <span class="op">~</span><span class="st"> </span>s  <span class="op">+</span><span class="st"> </span>yob_fct <span class="op">|</span><span class="st"> </span>q4 <span class="op">+</span><span class="st"> </span>yob_fct, <span class="dt">data =</span> ak91 )  <span class="co"># add exogenous vars on both sides of | !</span></span>
<span id="cb394-3"><a href="iv-applications.html#cb394-3"></a>mod[[<span class="st">&quot;2SLS_all&quot;</span>]] &lt;-<span class="st"> </span>estimatr<span class="op">::</span><span class="kw">iv_robust</span>(lnw <span class="op">~</span><span class="st"> </span>s  <span class="op">+</span><span class="st"> </span>yob_fct <span class="op">|</span><span class="st"> </span>qob_fct <span class="op">+</span><span class="st"> </span>yob_fct, <span class="dt">data =</span> ak91 )  <span class="co"># use all quarters as IVs</span></span>
<span id="cb394-4"><a href="iv-applications.html#cb394-4"></a></span>
<span id="cb394-5"><a href="iv-applications.html#cb394-5"></a><span class="co"># here is how to make the table:</span></span>
<span id="cb394-6"><a href="iv-applications.html#cb394-6"></a>rows &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">term =</span> <span class="kw">c</span>(<span class="st">&quot;Instruments&quot;</span>,<span class="st">&quot;Year of birth&quot;</span>),</span>
<span id="cb394-7"><a href="iv-applications.html#cb394-7"></a>                   <span class="dt">ols  =</span> <span class="kw">c</span>(<span class="st">&quot;none&quot;</span>,<span class="st">&quot;no&quot;</span>),</span>
<span id="cb394-8"><a href="iv-applications.html#cb394-8"></a>                   <span class="dt">SLS  =</span> <span class="kw">c</span>(<span class="st">&quot;Q4&quot;</span>,<span class="st">&quot;no&quot;</span>),</span>
<span id="cb394-9"><a href="iv-applications.html#cb394-9"></a>                   <span class="dt">ols_yr  =</span> <span class="kw">c</span>(<span class="st">&quot;none&quot;</span>,<span class="st">&quot;yes&quot;</span>),</span>
<span id="cb394-10"><a href="iv-applications.html#cb394-10"></a>                   <span class="dt">SLS_yr  =</span> <span class="kw">c</span>(<span class="st">&quot;Q4&quot;</span>,<span class="st">&quot;yes&quot;</span>),</span>
<span id="cb394-11"><a href="iv-applications.html#cb394-11"></a>                   <span class="dt">SLS_all  =</span> <span class="kw">c</span>(<span class="st">&quot;All Quarters&quot;</span>,<span class="st">&quot;yes&quot;</span>)</span>
<span id="cb394-12"><a href="iv-applications.html#cb394-12"></a>                   )</span>
<span id="cb394-13"><a href="iv-applications.html#cb394-13"></a><span class="kw">names</span>(rows)[<span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">6</span>)] &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;2SLS&quot;</span>,<span class="st">&quot;2SLS_yr&quot;</span>,<span class="st">&quot;2SLS_all&quot;</span>)</span>
<span id="cb394-14"><a href="iv-applications.html#cb394-14"></a>modelsummary<span class="op">::</span><span class="kw">msummary</span>(<span class="dt">models =</span> mod[<span class="kw">c</span>(<span class="st">&quot;ols&quot;</span>,<span class="st">&quot;2SLS&quot;</span>,<span class="st">&quot;ols_yr&quot;</span>,<span class="st">&quot;2SLS_yr&quot;</span>,<span class="st">&quot;2SLS_all&quot;</span>)], </span>
<span id="cb394-15"><a href="iv-applications.html#cb394-15"></a>                       <span class="dt">statistic =</span> <span class="st">&#39;std.error&#39;</span>,</span>
<span id="cb394-16"><a href="iv-applications.html#cb394-16"></a>                       <span class="dt">gof_omit =</span> <span class="st">&#39;DF|Deviance|AIC|BIC|R2|p.value|se_type|statistic|Log.Lik.|Num.Obs.|N&#39;</span>,</span>
<span id="cb394-17"><a href="iv-applications.html#cb394-17"></a>                       <span class="dt">title =</span> <span class="st">&quot;Adding Year as control, and more IVs&quot;</span>,</span>
<span id="cb394-18"><a href="iv-applications.html#cb394-18"></a>                       <span class="dt">add_rows =</span> rows,</span>
<span id="cb394-19"><a href="iv-applications.html#cb394-19"></a>                       <span class="dt">coef_omit =</span> <span class="st">&#39;yob_fct&#39;</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-199">Table 11.2: </span>Adding Year as control, and more IVs
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
ols
</th>
<th style="text-align:left;">
2SLS
</th>
<th style="text-align:left;">
ols_yr
</th>
<th style="text-align:left;">
2SLS_yr
</th>
<th style="text-align:left;">
2SLS_all
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:left;">
4.995
</td>
<td style="text-align:left;">
4.955
</td>
<td style="text-align:left;">
5.017
</td>
<td style="text-align:left;">
4.966
</td>
<td style="text-align:left;">
4.592
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.004)
</td>
<td style="text-align:left;">
(0.358)
</td>
<td style="text-align:left;">
(0.005)
</td>
<td style="text-align:left;">
(0.354)
</td>
<td style="text-align:left;">
(0.251)
</td>
</tr>
<tr>
<td style="text-align:left;">
s
</td>
<td style="text-align:left;">
0.071
</td>
<td style="text-align:left;">
0.074
</td>
<td style="text-align:left;">
0.071
</td>
<td style="text-align:left;">
0.075
</td>
<td style="text-align:left;">
0.105
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.000)
</td>
<td style="text-align:left;">
(0.028)
</td>
<td style="text-align:left;">
(0.000)
</td>
<td style="text-align:left;">
(0.028)
</td>
<td style="text-align:left;">
(0.020)
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:left;">
43782.556
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
4397.455
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Instruments
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
Q4
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
Q4
</td>
<td style="text-align:left;">
All Quarters
</td>
</tr>
<tr>
<td style="text-align:left;">
Year of birth
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:left;">
no
</td>
<td style="text-align:left;">
yes
</td>
<td style="text-align:left;">
yes
</td>
<td style="text-align:left;">
yes
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="IV-mech" class="section level2">
<h2><span class="header-section-number">11.3</span> IV Mechanics</h2>
<p>Let’s now look a little closer under the hood of our simple IV estimator. We want to understand how inference of IV relates to OLS inference, and what we can say about <em>weak</em> instruments, i.e. IVs with small predictive power in the first stage.</p>
<p>Let’s go back to our simple linear model</p>
<p><span class="math display" id="eq:iv0">\[
y = \beta_0 + \beta_1 x + u \tag{11.5}
\]</span></p>
<p>where we think that <span class="math inline">\(Cov(x,u) \neq 0\)</span>, hence, that <span class="math inline">\(x\)</span> is <em>endogenous</em> in this equation. By the way, IV estimation will work whether or not <span class="math inline">\(Cov(x,u) \neq 0\)</span>, but we should prefer OLS if <span class="math inline">\(x\)</span> is exogenous, as should become clear soon.</p>
<p>We now know that the conditions under which IV <span class="math inline">\(z\)</span> will deliver consistent estimates are the following:</p>
<ol style="list-style-type: decimal">
<li><strong>first stage</strong> or <strong>relevance</strong>: <span class="math inline">\(Cov(z,x) \neq 0\)</span></li>
<li><strong>IV exogeneity</strong>: <span class="math inline">\(Cov(z,u) = 0\)</span>: the IV is exogenous in the outcome equation.</li>
</ol>
<p>To reiterate, condition 2 here calls for <span class="math inline">\(z\)</span> to have no partial effect on <span class="math inline">\(y\)</span>, after <span class="math inline">\(x\)</span> and other omitted variables have been considered (they are in <span class="math inline">\(u\)</span>), hence, that <span class="math inline">\(z\)</span> is uncorrelated with <span class="math inline">\(u\)</span>. Figure <a href="iv-applications.html#fig:IV-dag2">11.6</a> shows a valid IV in panel A and an IV which violates condition 2 in panel B.</p>
<div class="figure" style="text-align: center"><span id="fig:IV-dag2"></span>
<img src="ScPoEconometrics_files/figure-html/IV-dag2-1.png" alt="A valid IV (A) and one where the exogeneity assumption is violated (B)." width="672" />
<p class="caption">
Figure 11.6: A valid IV (A) and one where the exogeneity assumption is violated (B).
</p>
</div>
<p>Let us now discuss how conditions 1. and 2. are helpful in <em>identifying</em> parameter <span class="math inline">\(\beta_1\)</span> above. By this we mean our ability to express <span class="math inline">\(\beta_1\)</span> in terms of population moments, which we can estimate from a sample of data. We start by computing the covariance of the instrument <span class="math inline">\(z\)</span> with outcome <span class="math inline">\(y\)</span>.</p>
<p><span class="math display">\[\begin{align}
Cov(z,y) &amp;= Cov(z, \beta_0 + \beta_1 x + u) \\
         &amp;= \beta_1 Cov(z,x) + Cov(z,u) 
\end{align}\]</span></p>
<p>Under condition 2. above (<em>IV exogeneity</em>), we have <span class="math inline">\(Cov(z,u)=0\)</span>, hence</p>
<p><span class="math display">\[
Cov(z,y) = \beta_1 Cov(z,x) 
\]</span>
and under condition 1. (<em>relevance</em>), we have <span class="math inline">\(Cov(z,x)\neq0\)</span>, so that we can divide the equation through to obtain</p>
<p><span class="math display">\[
\beta_1 =  \frac{Cov(z,y)}{Cov(z,x)}.
\]</span>
This shows that the parameter <span class="math inline">\(\beta_1\)</span> is <em>identified</em> via population moments <span class="math inline">\(Cov(z,y)\)</span> and <span class="math inline">\(Cov(z,x)\)</span>. What is more, we can <em>estimate</em> those moments via their <em>sample analogs</em>, hence we have as an IV estimator this expression, where we just <em>plug in</em> the sample estimators for the population moments:</p>
<p><span class="math display" id="eq:iv-estim">\[
\hat{\beta}_1 = \frac{\sum_{i=1}^n (z_i - \bar{z})(y_i - \bar{y})}{\sum_{i=1}^n (z_i - \bar{z})(x_i - \bar{x})} \tag{11.6}
\]</span>
The corresponding intercept estimate <span class="math inline">\(\hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x}\)</span> is identical to before (modulo using <a href="iv-applications.html#eq:iv-estim">(11.6)</a>).</p>
<p>Given both assumptions 1. and 2. are satisfied, we say that <em>the IV estimator is consistent for <span class="math inline">\(\beta_1\)</span></em>. This can also be written as</p>
<p><span class="math display">\[
\text{plim}(\hat{\beta}_1) = \beta_1
\]</span></p>
<p>meaning that, as the sample size <span class="math inline">\(n\)</span> increases, the <strong>probability limit</strong> (plim) of the estimator <span class="math inline">\(\beta_1\)</span> converges to the true parameter value with probability one.</p>
<div id="iv-inference" class="section level3">
<h3><span class="header-section-number">11.3.1</span> IV Inference</h3>
<p>Let us extend the homoskedasticity assumption <span class="math inline">\(z\)</span>, <span class="math inline">\(E(u^2|z) = \sigma^2\)</span>, such that the asymptotic (i.e. as the sample size gets very large) variance of the IV slope estimator is given by</p>
<p><span class="math display" id="eq:iv-var">\[
Var(\hat{\beta}_{1,IV}) = \frac{\sigma^2}{n \sigma_x^2 \rho_{x,z}^2}  \tag{11.7}
\]</span>
where <span class="math inline">\(\sigma_x^2\)</span> is the population variance of <span class="math inline">\(x\)</span>, <span class="math inline">\(\sigma^2\)</span> the one of <span class="math inline">\(u\)</span>, and <span class="math inline">\(\rho_{x,z}\)</span> is the population correlation between <span class="math inline">\(x\)</span> and <span class="math inline">\(z\)</span> - a measure of <em>how strongly</em> our IV and endogenous variable <span class="math inline">\(x\)</span> are correlated in the population.</p>
<p>You can see 2 important things in equation <a href="iv-applications.html#eq:iv-var">(11.7)</a>:</p>
<ol style="list-style-type: decimal">
<li>Without the term <span class="math inline">\(\rho_{x,z}^2\)</span> in the denominator, this is identical to the variance of the OLS slope estimator.</li>
<li>As with the variance of the OLS slope estimator, as sample size <span class="math inline">\(n\)</span> increases, the variance decreases.</li>
</ol>
<p>It is convenient to replace <span class="math inline">\(\rho_{x,z}^2\)</span> with <span class="math inline">\(R_{x,z}^2\)</span>, i.e. the R-squared of a regression of <span class="math inline">\(x\)</span> on <span class="math inline">\(z\)</span> - in a single regressor model we have this exact correspondence. It is convenient because we rewrite the variance of the IV slope now as</p>
<p><span class="math display">\[
Var(\hat{\beta}_{1,IV}) = \frac{\sigma^2}{n \sigma_x^2 R_{x,z}^2}
\]</span></p>
<ol style="list-style-type: decimal">
<li>Given <span class="math inline">\(R_{x,z}^2 &lt; 1\)</span> in most real life situations, we have that <span class="math inline">\(Var(\hat{\beta}_{1,IV}) &gt; Var(\hat{\beta}_{1,OLS})\)</span> almost certainly.</li>
<li>The higher the correlation between <span class="math inline">\(z\)</span> and <span class="math inline">\(x\)</span>, the closer their <span class="math inline">\(R_{x,z}^2\)</span> is to 1. With <span class="math inline">\(R_{x,z}^2 = 1\)</span> we get back to the OLS variance. This is no surprise, because that implies that in fact <span class="math inline">\(z = x\)</span>.</li>
</ol>
<p>So, if you have a valid, exogenous regressor <span class="math inline">\(x\)</span>, you should <em>not</em> perform IV estimation using <span class="math inline">\(z\)</span> to obtain <span class="math inline">\(\hat{\beta}\)</span>, since your variance will be unnecessarily large.</p>
<div id="returns-to-education-for-married-women" class="section level4">
<h4><span class="header-section-number">11.3.1.1</span> Returns to Education for Married Women</h4>
<p>Consider the following model for married women’s wages:</p>
<p><span class="math display">\[
\log wage = \beta_0 + \beta_1 educ + u
\]</span>
Let’s run an OLS on this, and then compare it to an IV estimate using <em>father’s education</em>. Keep in mind that this is a valid IV <span class="math inline">\(z\)</span> if</p>
<ol style="list-style-type: decimal">
<li><em>fatheduc</em> and <em>educ</em> are correlated</li>
<li><em>fatheduc</em> and <span class="math inline">\(u\)</span> are not correlated.</li>
</ol>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="iv-applications.html#cb395-1"></a><span class="kw">data</span>(mroz,<span class="dt">package =</span> <span class="st">&quot;wooldridge&quot;</span>)</span>
<span id="cb395-2"><a href="iv-applications.html#cb395-2"></a>mods =<span class="st"> </span><span class="kw">list</span>()</span>
<span id="cb395-3"><a href="iv-applications.html#cb395-3"></a>mods<span class="op">$</span>OLS &lt;-<span class="st"> </span><span class="kw">lm</span>(lwage <span class="op">~</span><span class="st"> </span>educ, <span class="dt">data =</span> mroz)</span>
<span id="cb395-4"><a href="iv-applications.html#cb395-4"></a>mods[[<span class="st">&#39;First Stage&#39;</span>]] &lt;-<span class="st"> </span><span class="kw">lm</span>(educ <span class="op">~</span><span class="st"> </span>fatheduc, <span class="dt">data =</span> <span class="kw">subset</span>(mroz, inlf <span class="op">==</span><span class="st"> </span><span class="dv">1</span>))</span>
<span id="cb395-5"><a href="iv-applications.html#cb395-5"></a>mods<span class="op">$</span>IV  &lt;-<span class="st"> </span>estimatr<span class="op">::</span><span class="kw">iv_robust</span>(lwage <span class="op">~</span><span class="st"> </span>educ <span class="op">|</span><span class="st"> </span>fatheduc, <span class="dt">data =</span> mroz)</span>
<span id="cb395-6"><a href="iv-applications.html#cb395-6"></a>modelsummary<span class="op">::</span><span class="kw">modelsummary</span>(mods, <span class="dt">gof_map =</span> gm, <span class="dt">gof_omit =</span> gom, <span class="dt">title =</span> <span class="st">&quot;Mroz female labor supply and wage data.&quot;</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:mroz1">Table 11.3: </span>Mroz female labor supply and wage data.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
OLS
</th>
<th style="text-align:left;">
First Stage
</th>
<th style="text-align:left;">
IV
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:left;">
-0.185
</td>
<td style="text-align:left;">
10.237
</td>
<td style="text-align:left;">
0.441
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.185)
</td>
<td style="text-align:left;">
(0.276)
</td>
<td style="text-align:left;">
(0.467)
</td>
</tr>
<tr>
<td style="text-align:left;">
educ
</td>
<td style="text-align:left;">
0.109
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
0.059
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.014)
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.037)
</td>
</tr>
<tr>
<td style="text-align:left;">
fatheduc
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
0.269
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.029)
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Obs.
</td>
<td style="text-align:left;">
428
</td>
<td style="text-align:left;">
428
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
R2
</td>
<td style="text-align:left;">
0.118
</td>
<td style="text-align:left;">
0.173
</td>
<td style="text-align:left;">
0.093
</td>
</tr>
<tr>
<td style="text-align:left;">
N
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
428
</td>
</tr>
</tbody>
</table>
<p>The results in table <a href="iv-applications.html#tab:mroz1">11.3</a> show in the first column that an additional year of education implies an 11% increase in annual wages for women. This is a standard OLS estimator which be biased because of <em>ability bias</em>.</p>
<p>In the second column we show the first stage of the IV procedure. We see that <em>fatheduc</em> is indeed a statistically significant predictor of <span class="math inline">\(educ\)</span>: Each additional year of father’s education increases women’s education by more than a quarter of a year (0.269). Also important, we observe that the <span class="math inline">\(R^2\)</span> here is about 17%.</p>
<p>Turning to the final IV estimate in the third column, we can see that using <em>fatheduc</em> as an IV reduces the return to education by about half to 5.9%! This result <em>suggests</em> that OLS is biased upwards (for example by ability bias). But let’s compare the standard errors of OLS and IV estimates, which are 0.014 for OLS vs 0.037 for IV. This can be seen in figure <a href="iv-applications.html#fig:se-plot">11.7</a>. You can clearly see that the standard errors of both estimators overlap, hence from this alone we cannot conclude they are different (we need a special statistical test to decide this).</p>
<div class="figure" style="text-align: center"><span id="fig:se-plot"></span>
<img src="ScPoEconometrics_files/figure-html/se-plot-1.png" alt="OLS vs IV Standard Errors" width="672" />
<p class="caption">
Figure 11.7: OLS vs IV Standard Errors
</p>
</div>
</div>
</div>
<div id="iv-with-a-poor-instrument" class="section level3">
<h3><span class="header-section-number">11.3.2</span> IV with a Poor Instrument</h3>
<p>We have seen that IV will produce consistent estimates under our stated assumptions. However, even under valid assumption, we get large IV standard errors if the the correlation between IV and endogenous <span class="math inline">\(x\)</span> is small.<br />
What is even worse is that <em>even if</em> we have only very small correlation between <span class="math inline">\(z\)</span> and <span class="math inline">\(u\)</span>, so that we might <em>almost</em> be happy to assume exogeneity, a small corrleation between <span class="math inline">\(x\)</span> and <span class="math inline">\(z\)</span> can produce <strong>inconsistent</strong> estimates. To see this, consider the probability limit of the IV estimator again</p>
<p><span class="math display">\[
\text{plim}(\hat{\beta}_{1,IV}) = \beta_1 + \frac{Cor(z,u)}{Cor(z,x)} \cdot \frac{\sigma_u}{\sigma_x}
\]</span></p>
<p>The interesting part here involves the correlation terms. <em>Even if</em> <span class="math inline">\(Cor(z,u)\)</span> is very small, a <strong>weak instrument</strong>, i.e. one with only a small absolute value for <span class="math inline">\(Cor(z,x)\)</span> will blow up this second term in the probability limit. This would mean that even with a very big sample size <span class="math inline">\(n\)</span>, our estimator would <em>not</em> converge to the true population parameter <span class="math inline">\(\beta_1\)</span>, because we are using a weak instrument.</p>
<p>To illustrate this point, let’s assume we want to look at the impact of number of packs of cigarettes smoked per day by pregnant women (<em>packs</em>) on the birthweight of their child (<em>bwght</em>):</p>
<p><span class="math display">\[
\log(bwght) = \beta_0 + \beta_1 packs + u
\]</span></p>
<p>We are worried that smoking behavior is correlated with a range of other health-related variables which are in <span class="math inline">\(u\)</span> and which could impact the birthweight of the child. So we look for an IV. Suppose we use the price of cigarettes (<em>cigprice</em>), assuming that the price of cigarettes is uncorrelated with factors in <span class="math inline">\(u\)</span>. Let’s run the first stage of <em>cigprice</em> on <em>packs</em> and then let’s show the 2SLS estimates:</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="iv-applications.html#cb396-1"></a><span class="kw">data</span>(bwght, <span class="dt">package =</span> <span class="st">&quot;wooldridge&quot;</span>)</span>
<span id="cb396-2"><a href="iv-applications.html#cb396-2"></a>mods &lt;-<span class="st"> </span><span class="kw">list</span>()</span>
<span id="cb396-3"><a href="iv-applications.html#cb396-3"></a>mods[[<span class="st">&quot;First Stage&quot;</span>]] &lt;-<span class="st"> </span><span class="kw">lm</span>(packs <span class="op">~</span><span class="st"> </span>cigprice, <span class="dt">data =</span> bwght)</span>
<span id="cb396-4"><a href="iv-applications.html#cb396-4"></a>mods[[<span class="st">&quot;IV&quot;</span>]] &lt;-<span class="st"> </span>estimatr<span class="op">::</span><span class="kw">iv_robust</span>(<span class="kw">log</span>(bwght) <span class="op">~</span><span class="st">  </span>packs <span class="op">|</span><span class="st"> </span>cigprice, <span class="dt">data =</span> bwght)</span>
<span id="cb396-5"><a href="iv-applications.html#cb396-5"></a><span class="kw">modelsummary</span>(mods, <span class="dt">gof_map =</span> gm, </span>
<span id="cb396-6"><a href="iv-applications.html#cb396-6"></a>             <span class="dt">gof_omit =</span> gom, </span>
<span id="cb396-7"><a href="iv-applications.html#cb396-7"></a>             <span class="dt">title =</span> <span class="st">&quot;IV regression with weak instrument *cigprice*&quot;</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:bw">Table 11.4: </span>IV regression with weak instrument <em>cigprice</em>
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
First Stage
</th>
<th style="text-align:left;">
IV
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:left;">
0.067
</td>
<td style="text-align:left;">
4.448
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.103)
</td>
<td style="text-align:left;">
(0.940)
</td>
</tr>
<tr>
<td style="text-align:left;">
cigprice
</td>
<td style="text-align:left;">
0.000
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(0.001)
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
packs
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
2.989
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
(8.996)
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Obs.
</td>
<td style="text-align:left;">
1388
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
R2
</td>
<td style="text-align:left;">
0.000
</td>
<td style="text-align:left;">
-23.230
</td>
</tr>
<tr>
<td style="text-align:left;">
N
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
1388
</td>
</tr>
</tbody>
</table>
<p>The first column of table <a href="iv-applications.html#tab:bw">11.4</a> shows that the first stage is <em>very</em> weak. The partial effect of <em>cigprice</em> on <em>packs</em> smoked is zero! People don’t seem to care a great deal about the price of cigarettes (at least in the range of price variation observed in this dataset). The <span class="math inline">\(R^2\)</span> of that first stage is thus zero. What do we get if we use that IV nonetheless in a 2SLS estimation as in column 2? We get a huge coefficient of unexpected sign on <em>packs</em> (smoking more increases birthweight? 🤔), with very large standard error, so statistically speaking, we cannot distinguish this from zero. What is more important, however, is that even if they <em>were</em> significant, the estimates of column 2 are <strong>invalid</strong>. The <em>relevance</em> of the IV condition is clearly not satisfied, hence, invalid approach.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-angristkruegerIV">
<p>Angrist, Joshua D, and Alan B Krueger. 2001. “Instrumental Variables and the Search for Identification: From Supply and Demand to Natural Experiments.” <em>Journal of Economic Perspectives</em> 15 (4): 69–85.</p>
</div>
<div id="ref-angristkrueger">
<p>Angrist, Joshua D., and Alan B. Krueger. 1991. “Does Compulsory School Attendance Affect Schooling and Earnings?” <em>The Quarterly Journal of Economics</em> 106 (4): 979–1014. <a href="https://doi.org/10.2307/2937954">https://doi.org/10.2307/2937954</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="13">
<li id="fn13"><p>It’s called reduced form because this second equation is supposed to be derived from a true underlying structural model.<a href="iv-applications.html#fnref13" class="footnote-back">↩︎</a></p></li>
<li id="fn14"><p>Code in this section comes from the great <a href="https://jrnold.github.io/masteringmetrics/">mastering metrics with R</a> by J Arnold 👏 🙏<a href="iv-applications.html#fnref14" class="footnote-back">↩︎</a></p></li>
<li id="fn15"><p>the <em>robust</em> here refers to the fact that the <code>estimatr</code> package by default chooses formulae to compute standard errors which are correcting for heteroskedasticity - we have encountered this term before in <a href="std-errors.html#violating">6.6.2</a>. See details <a href="https://declaredesign.org/r/estimatr/articles/mathematical-notes.html">here</a><a href="iv-applications.html#fnref15" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="IV.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="panel-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/ScPoEcon/ScPoEconometrics/edit/master/11-IV2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["ScPoEconometrics.pdf", "ScPoEconometrics.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
