app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(i_std = 1.6)
app$setInputs(s_std = 0.8)
app$setInputs(i_std = 2.5)
app$setInputs(i_std = 2.6)
app$setInputs(i_std = 2.7)
app$setInputs(i_std = 2.8)
app$setInputs(i_std = 2.9)
app$setInputs(i_std = 2.6)
app$setInputs(i_std = 2.5)
app$setInputs(i_std = 2.4)
app$snapshot()
app$setInputs(std = TRUE)
app$setInputs(i_std = 0.7)
app$setInputs(i_std = 0.6)
app$setInputs(i_std = 0.2)
app$setInputs(i_std = 0.1)
app$setInputs(i_std = 0)
app$setInputs(s_std = 0.6)
