app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(i_std = 1.5)
app$setInputs(s_std = 1.5)
app$setInputs(s_std = 1)
app$setInputs(i_std = 2.5)
app$setInputs(i_std = 2)
app$setInputs(i_std = 2.5)
app$setInputs(s_std = 0.9)
app$setInputs(s_std = 0.8)
app$snapshot()
app$setInputs(std = TRUE)
app$setInputs(i_std = 2)
app$setInputs(i_std = 1.5)
app$setInputs(i_std = 0.5)
app$setInputs(i_std = 0)
app$setInputs(s_std = 0.6)
app$snapshot()
