app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(std = TRUE)
app$snapshot()
app$setInputs(i_std = -1)
app$setInputs(s_std = 1.4)
app$setInputs(std = FALSE)
app$snapshot()
app$setInputs(s_std = 0.8)
app$setInputs(i_std = -0.5)
app$setInputs(i_std = 0)
app$setInputs(s_std = 1.1)
app$setInputs(s_std = 0.9)
app$setInputs(s_std = 1)
app$setInputs(s_std = 1.2)
app$setInputs(s_std = 1.5)
app$setInputs(s_std = 1.6)
app$setInputs(i_std = 0.5)
app$setInputs(i_std = 1)
app$setInputs(s_std = 1.5)
app$setInputs(i_std = 0.5)
app$setInputs(i_std = 0)
app$setInputs(i_std = -0.5)
app$setInputs(s_std = 1.8)
app$setInputs(s_std = 1.7)
app$setInputs(s_std = 2)
app$setInputs(std = TRUE)
app$snapshot()
