app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(c = 0.45)
app$setInputs(c = -0.35)
app$setInputs(c = -0.75)
app$setInputs(c = -1)
app$setInputs(c = 1)
app$snapshot()
