---
title: "tasks for session 1"
author: "Florian Oswald"
date: "8/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# task 1

1. Create a vector of five ones, i.e. `[1,1,1,1,1]`
  `rep(1,5)`
1. Notice that the colon operator `a:b` is just short for *construct a sequence **from** `a` **to** `b`*. Create a vector the counts down from 10 to 0, i.e. it looks like `10,9,8,7,6,5,4,3,2,1,0`!
  `10:0`
1. the `rep` function takes additional arguments `times` (as above), and `each`, which tells you how often *each element* should be repeated (as opposed to the entire input vector). Use `rep` to create a vector that looks like this: `1 1 1 2 2 2 3 3 3 1 1 1 2 2 2 3 3 3`
  `rep(1:3,times=2,each=3)`
  
# task 2

1. Create a vector filled with 10 numbers drawn from the uniform distribution (hint: use function `runif`) and store them in `x`. `x = runif(10)`
1. Using logical subsetting as above, get all the elements of `x` which are larger than 0.5, and store them in `y`. `y = x[x>0.5]`
1. using the function `which`, store the *indices* of all the elements of `x` which are larger than 0.5 in `iy`. `iy = which(x>0.5)`
1. Check that `y` and `x[iy]` are identical. `identical(y,x[iy])` or `all(y == x[iy])`

# Task 3

1. Create a vector containing `1,2,3,4,5` called v. `v = 1:5`
1. Create a (2,5) matrix `m` containing the data `1,2,3,4,5,6,7,8,9,10`. The first row should be `1,2,3,4,5`. `m = matrix(data = 1:10,nrow=2,ncol=5,byrow=T)`
1. Perform matrix multiplication of `m` with `v`. Use the command `%*%`. What dimension does the output have? `dim(m%*% v)`,
1. Why does `v %*% m` not work? non-conformable


# Task 4

1. Copy and paste the above code for `ex_list` into your R session. Remember that `list` can hold any kind of `R` object. Like...another list! So, create a new list `new_list` that has two fields: a first field called "this" with string content `"is awesome"`, and a second field called "ex_list" that contains `ex_list`. `new_list = list(this = "is awesome", ex_list = ex_list)`
1. Accessing members is like in a plain list, just with several layers now. Get the element `c` from `ex_list` in `new_list`! `new_list$ex_list$c`
1. Compose a new string out of the first element in `new_list`, the element under label `this`. Use the function `paste` to print `R is awesome` to your screen. `paste("R",new_list$this)`

# Task 5


1. Make sure to have the `mpg` dataset loaded by typing `data(mpg)` (and `library(ggplot2)` if you haven't!). Use the `table` function to find out how many cars were built by *mercury*? `table(mpg$manufacturer)`, `4`.
1. What is the average year the audi's were built in this dataset? Use the function `mean` on the subset of column `year` that corresponds to `audi`. (Be careful: subsetting a `tibble` returns a `tibble` (and not a vector)!. so get the `year` column after you have subset the `tibble`.) `mean(subset(mpg,subset=manufacturer=="audi")$year)`, `mean(mpg[mpg$manufacturer=="audi","year"]$year)`
1. Use the `dplyr` piping syntax from above first with `group_by` and then with `summarise(newvar=your_expression)` to find the mean `year` by manufacturer!
```
mpg %>%
  group_by(manufacturer) %>%
  summarise(year=mean(year))
```

