---
title: "Anscombe's Quartet"
runtime: shiny_prerendered
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(datasauRus)
```

```{r, echo=FALSE}
shinyUI(fluidPage(
  fluidRow(checkboxGroupInput(inputId = "addr", label = "Show:",
                       choices = list("Line of Best Fit" = 1,
                                      "Means" = 2,
                                      "Standard Deviations" = 3,
                                      "r coefficient" = 4))),
  fluidRow(plotOutput("quartet"))
))
```

```{r, context="server"}
output$quartet <- renderPlot({
  #Plotting function
  plot_quartet <- function(mean = F, sd = F, fit = F, r = F){
    ff <- y ~ x
    mods <- setNames(as.list(1:4), paste0("lm", 1:4))
    for(i in 1:4){
      ff[2:3] <- lapply(paste0(c("y","x"), i), as.name)
      mods[[i]] <- lmi <- lm(ff, data = anscombe)
    }
    
    op <- par(mfrow = c(2, 2), mar = 0.1+c(4,4,1,1), oma =  c(0, 0, 2, 0))
    for(i in 1:4) {
      ff[2:3] <- lapply(paste0(c("y","x"), i), as.name)
      plot(ff, data = anscombe, col = "royalblue", pch = 21, bg = "blue", cex = 1.2,
           xlim = c(3, 19), ylim = c(3, 13), main=paste("dataset",i))
      
      if (fit == T){
        abline(mods[[i]], col = "green")
      }
      
      if (mean == T){
        abline(h = mean(anscombe[[paste0("y", i)]]), lty = "dashed")
        abline(v = mean(anscombe[[paste0("x", i)]]), lty = "dashed")
      }
      
      if (sd == T){
        text(x = 5.5, y = 11,
             labels = paste0("sd_y = ", round(sd(anscombe[[paste0("y", i)]]), 2)),
             cex = 1.1)
        text(x = 5.5, y = 9.5,
             labels = paste0("sd_x = ", round(sd(anscombe[[paste0("x", i)]]), 2)),
             cex = 1.1)
      }
      
      if (r == T){
        text(x = 15, y = 5,
             labels = paste0("r = ", round(cor(anscombe[[paste0("y", i)]], 
                                               anscombe[[paste0("x", i)]]), 2)),
             cex = 1.1)
      }
      
    }
    par(op)
  }
  # Plot
  
  f <- 1 %in% input$addr
  m <- 2 %in% input$addr
  s <- 3 %in% input$addr
  r <- 4 %in% input$addr
  
  plot_quartet(mean = m, sd = s, fit = f, r = r)
  
})
```

## The Datasaurus Dozen

Believe it or not, the following 13 dataset all have the same *linear summary statistics*:


| Statistic | Value |
|  ---       | ---  | 
| $\bar{x}$    |`54.26` |
| $\bar{y}$    |`47.83` |
| $\sigma_{x}$ |`16.765`|
| $\sigma_{y}$ |`26.935`|
| $r_{xy}$     |`-0.065`|


```{r, echo=FALSE}
shinyUI(fluidPage(
  fluidRow(sliderInput(inputId = "dataset", label = "Dataset:", min = 1, max = 13, value = 1, step = 1)),
  fluidRow(plotOutput("dino"))
))
```

```{r, context="server"}
output$dino <- renderPlot({
  
  #Plotting function
  dz <- datasaurus_dozen
  
  plot_dino <- function(i){
    plot(y~x, dz[dz$dataset == unique(dz$dataset)[i], ], 
         col = "royalblue", pch = 21, bg = "blue", cex = 1, asp=1,
         ylim = c(0, 100), xlim = c(-100, 200), 
         main = paste0('DataSet', i))
    abline(lm(formula = y~x, data = dz[dz$dataset == "dino", ]), col = 'green')
    #abline(h = mean(dz[dz$dataset == "dino", ]$x), lty = 'dashed')
    #abline(v = mean(dz[dz$dataset == "dino", ]$y), lty = 'dashed')
  }
  
  plot_dino(input$dataset)
  
})
```