---
title: "reg_app"
runtime: shiny_prerendered
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

## Simple Fit

```{r, echo=FALSE}
shinyUI(fluidPage(
  sidebarPanel(sliderInput("i", "Intercept", min = -4,
                           max = 4, step = 2, value = -2),
               sliderInput("s", "Slope", min = -2,
                           max = 2, step = .5, value = 1),
               br(),
               br(),
               
               sliderInput("ex", "Example:", min = 1,
                           max = 10, step = 1, value = 1, ticks = FALSE),
               sliderInput("noise", "Noise Level:", min = 0,
                           max = 2, step = .5, value = 1),
               
               textOutput("userguess")),
  
  mainPanel(
    plotOutput("regPlot"),
    textOutput("MSE"))))
```


```{r, context="server"}

output$userguess <- renderText({

  a <- input$i
  b <- input$s
  paste0("Your guess:\n y = ", a, " + ", b, "x")
  
})

output$regPlot <- renderPlot({
 
  set.seed(input$ex)
  
  # Generate Random Data
  x <- rnorm(n = 20, mean = 0, sd = 4)
  coeffslope <- c(-2, -1.5, -1, -.5, 0, .5, 1, 1.5, 2)
  coeffint <- c(-4, -2, 0, 2, 4)
  a_true <- sample(coeffint, size = 1)
  b_true <- sample(coeffslope, size = 1)
  y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = input$noise)
  # True DGP: y = a_t + b_t * x + u
  
      
      
  # a = intercept, b = slope (user input)
  a <- input$i
  b <- input$s
      
      
  # plot
  expr <- function(x) a + b*x
  errors <- (a + b*x) - y 
  
  plot(x, y, type = "p", pch = 21, col = "blue", bg = "royalblue", asp=1,
       xlim = c(min(c(x, y))-1, max(c(x, y))+1),
       ylim = c(min(c(x, y))-1, max(c(x, y))+1),
       main = "The Linear Regression", frame.plot = FALSE,
       cex = 1.2)
  
  legend("topleft", legend = paste0("r (correlation coefficient) = ", round(cor(x, y), 3)))
  
  if ((a == a_true) && (b == b_true)){
    curve(expr = expr, from = min(x)-10, to = max(x)+10, add = T, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "green")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 0, green = 1, blue = 0, alpha = 0.1), border = NA)
  } else {
    curve(expr =expr , from = min(x)-10, to = max(x)+10, add = T, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "red")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 1, green = 0, blue = 0, alpha = 0.1), border = NA)
  }

})

output$MSE <- renderText({
  set.seed(input$ex)
  x <- rnorm(n = 20, mean = 0, sd = 4)
  coeffslope <- c(-2, -1.5, -1, -.5, 0, .5, 1, 1.5, 2)
  coeffint <- c(-4, -2, 0, 2, 4)
  a_true <- sample(coeffint, size = 1)
  b_true <- sample(coeffslope, size = 1)
  y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = input$noise)
  a <- input$i
  b <- input$s

  errors <- (a + b*x) - y
  
  paste0("Total Sum of Squared Errors = ", sum(errors^2))
})
```

### Simplest App Possible

```{r, echo=FALSE}
shinyUI(fluidPage(
  sidebarPanel(sliderInput("i_simple", "Intercept", min = -4,
                           max = 4, step = .5, value = .5),
               sliderInput("s_simple", "Slope", min = -2,
                           max = 2, step = .5, value = -1),
               br(),
               br(),
               
               textOutput("userguess_simple")),
  
  mainPanel(
    plotOutput("regPlot_simple"))))
```


```{r, context="server"}

output$userguess_simple <- renderText({

  a <- input$i_simple
  b <- input$s_simple
  paste0("Your guess:\n y = ", a, " + ", b, "x")
  
})

output$regPlot_simple <- renderPlot({
 
  set.seed(19)
  
  # Generate Random Data
  x <- rnorm(n = 20, mean = 2, sd = 4)
  
  a_true <- -2
  b_true <- 1.5
  y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = 1)
  # True DGP: y = -2 + 1.5 * x + u
  
      
      
  # a = intercept, b = slope (user input)
  a <- input$i_simple
  b <- input$s_simple
      
      
  # plot
  expr <- function(x) a + b*x
  errors <- (a + b*x) - y 
  
  plot(x, y, type = "p", pch = 21, col = "blue", bg = "royalblue", asp=1,
       xlim = c(min(c(x, y))-1, max(c(x, y))+1),
       ylim = c(min(c(x, y))-1, max(c(x, y))+1),
       main = "Fit the data!", frame.plot = FALSE,
       cex = 1.2)
  
  if ((a == a_true) && (b == b_true)){
    curve(expr = expr, from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "green")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 0, green = 1, blue = 0, alpha = 0.05), border = NA)
  } else {
    curve(expr =expr , from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "red")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 1, green = 0, blue = 0, alpha = 0.05), border = NA)
  }

})
```




## Fit with no slope
What if you could only use one fixed number (i.e. a horizontal line) to fit $Y$ ?

```{r, echo=FALSE}
shinyUI(fluidPage(
  sidebarPanel(
    
    radioButtons("const", label = h4("Parameter"),
    choices = list("Intercept only" = 1,
                   "Slope only" = 2,
                   "Both" = 3), 
    selected = 1),
    
    conditionalPanel(condition = "input.const == 1",
                     wellPanel(sliderInput("i2", "Intercept", min = -5, max = 5, step = .1, value = -2),
                     h5("Slope = 0"))),
    
    conditionalPanel(condition = "input.const == 2",
                     wellPanel(h5("Intercept = 0"),
                     sliderInput("s2", "Slope", min = -5, max = 5, step = .1, value = -2)),
                     checkboxInput(inputId = "demean", "de-Mean x and y", value = F)),
    
    conditionalPanel(condition = "input.const == 3",
                     wellPanel(sliderInput("ib", "Intercept", min = -5, max = 5, step = .5, value = -2),
                     sliderInput("sb", "Slope", min = -5, max = 5, step = .5, value = -1))),
    
               
    br(),
               
    br(),
               
    sliderInput("ex2", "Example:", min = 1,
                           max = 3, step = 1, value = 1, ticks = FALSE),
    
    textOutput("userguess2")),
  
  mainPanel(
    plotOutput("regPlot2"),
    textOutput("MSE2"))))
```


```{r, context="server"}

output$userguess2 <- renderText({
  
  if (input$const == 1){
    a <- input$i2
    paste0("Your guess:\n y = ", a)
  } else if (input$const == 2) {
    b <- input$s2
    if (input$demean == T){
      paste0("Your guess:\n [y - mean(y)] = ", b, "[x - mean(x)]")
    } else {
      paste0("Your guess:\n y = ", b, "x")
    }
    
  } else {
    a <- input$ib
    b <- input$sb
    paste0("Your guess:\n y = ", a, " + ", b, "x")
  }

  
  
})

output$regPlot2 <- renderPlot({
 
  set.seed(input$ex2)
  
  # Generate Random Data
  x <- rnorm(n = 20, mean = 2, sd = 2)
  coeffslope <- c(2, 0, -1)
  coeffint <- c(-2, .5, 3)
  a_true <- coeffint[input$ex2]
  b_true <- coeffslope[input$ex2]
  y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = 1)
  
  
      
  if (input$const == 1){     
    # a = intercept (user input)
    a <- input$i2
        
    # plot
    #expr <- function(x) a
    errors <- (a) - y 
    
    plot(x, y, type = "p", pch = 21, col = "blue", bg = "royalblue", asp=1,
         xlim = c(min(c(x, y))-1, max(c(x, y))+1),
         ylim = c(-10, 10),
         main = "The Linear Regression (with no slope!)", frame.plot = FALSE,
         cex = 1.2)
    abline(h = mean(y), col = "black", lty = "dotted")
    text(x = min(x), y = mean(y), labels = "Mean of Y", pos = 3)
    
    legend("topleft", legend = paste0("r (correlation coefficient) = ", round(cor(x, y), 3)))
    
    if (near(a, mean(y), tol = .05)){
      #curve(expr = expr, from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
      abline(h = a, col = "black")
      segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "green")
      rect(xleft = x, ybottom = y,
           xright = x + abs(errors), ytop = y + errors, density = -1,
           col = rgb(red = 0, green = 1, blue = 0, alpha = 0.1), border = NA)
    } else {
      #curve(expr = expr , from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
      abline(h = a, col = "black")
      segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "red")
      rect(xleft = x, ybottom = y,
           xright = x + abs(errors), ytop = y + errors, density = -1,
           col = rgb(red = 1, green = 0, blue = 0, alpha = 0.1), border = NA)
    }
  } else if (input$const == 2){
    
    if (input$demean == T){
      x <- rnorm(n = 20, mean = 2, sd = 2)
      x <- x - mean(x)
      coeffslope <- c(2, 0, -1)
      coeffint <- c(-2, .5, 3)
      a_true <- coeffint[input$ex2]
      b_true <- coeffslope[input$ex2]
      y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = 1)
      y <- y - mean(y)
    }
        
    b <- input$s2
    
        
        
    # plot
    
    
    
    expr <- function(x) b*x
    errors <- (b*x) - y
    
    
     
    
    plot(x, y, type = "p", pch = 21, col = "blue", bg = "royalblue", asp=1,
         xlim = c(-10, 10),
         ylim = c(-10, 10),
         main = "The Linear Regression (with no intercept term!)", frame.plot = FALSE,
         cex = 1.2)
    abline(h = 0, col = 'grey')
    abline(v = 0, col = 'grey')

    
    legend("topleft", legend = paste0("r (correlation coefficient) = ", round(cor(x, y), 3)))
    
    best_b = sum(x*y)/sum(x^2)
    
    if (near(b, best_b, .05)){
      curve(expr = expr, from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
      segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "green")
      rect(xleft = x, ybottom = y,
           xright = x + abs(errors), ytop = y + errors, density = -1,
           col = rgb(red = 0, green = 1, blue = 0, alpha = 0.1), border = NA)
    } else {
      curve(expr = expr , from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
      segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "red")
      rect(xleft = x, ybottom = y,
           xright = x + abs(errors), ytop = y + errors, density = -1,
           col = rgb(red = 1, green = 0, blue = 0, alpha = 0.1), border = NA)
    }
    
  } else {
    
    # a = intercept, b = slope (user input)
    a <- input$ib
    b <- input$sb
        
        
    # plot
    expr <- function(x) a + b*x
    errors <- (a + b*x) - y 
    
    plot(x, y, type = "p", pch = 21, col = "blue", bg = "royalblue", asp=1,
         xlim = c(min(c(x, y))-1, max(c(x, y))+1),
         ylim = c(-10, 10),
         main = "The Linear Regression", frame.plot = FALSE,
         cex = 1.2)
    
    legend("topleft", legend = paste0("r (correlation coefficient) = ", round(cor(x, y), 3)))
    
    b_best = cov(x, y)/var(x)
    a_best = mean(y) - b_best*mean(x)
    
    if (near(a, a_best, tol = .25) && (near(b, b_best, tol = .25))){
      curve(expr = expr, from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
      segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "green")
      rect(xleft = x, ybottom = y,
           xright = x + abs(errors), ytop = y + errors, density = -1,
           col = rgb(red = 0, green = 1, blue = 0, alpha = 0.1), border = NA)
    } else {
      curve(expr =expr , from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
      segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "red")
      rect(xleft = x, ybottom = y,
           xright = x + abs(errors), ytop = y + errors, density = -1,
           col = rgb(red = 1, green = 0, blue = 0, alpha = 0.1), border = NA)
    }
    
  }

})

output$MSE2 <- renderText({
  set.seed(input$ex2)
  
  # Generate Random Data
  x <- rnorm(n = 20, mean = 2, sd = 2)
  coeffslope <- c(2, 0, -1)
  coeffint <- c(-2, .5, 3)
  a_true <- coeffint[input$ex2]
  b_true <- coeffslope[input$ex2]
  y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = 1)
  
  if (input$const == 1){
    a <- input$i2

    errors <- (a) - y
  
    paste0("Total Sum of Squared Errors = ", sum(errors^2))
    
  } else if (input$const == 2){
    
    if (input$demean == T){
      x <- rnorm(n = 20, mean = 2, sd = 2)
      x <- x - mean(x)
      coeffslope <- c(2, 0, -1)
      coeffint <- c(-2, .5, 3)
      a_true <- coeffint[input$ex2]
      b_true <- coeffslope[input$ex2]
      y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = 1)
      y <- y - mean(y)
    }
    
    b <- input$s2

    errors <- (b*x) - y
  
    paste0("Total Sum of Squared Errors = ", sum(errors^2))
    
  } else {
    b <- input$sb
    a <- input$ib

    errors <- (a + (b*x)) - y
  
    paste0("Total Sum of Squared Errors = ", sum(errors^2))
  }
  
})
```

## Fit of $Y$ onto $X \in \{0, 1\}$ (and a constant)

```{r, echo=FALSE}
shinyUI(fluidPage(
  sidebarPanel(sliderInput("i_dummy", "Intercept", min = 0,
                           max = 5, step = .25, value = 3),
               sliderInput("s_dummy", "Slope", min = -1,
                           max = 5, step = .25, value = 2),
               
               checkboxInput("meany_x0", "Show E[Y | X = 0]", value = FALSE),
               checkboxInput("meany_x1", "Show E[Y | X = 1]", value = FALSE),
               
               br(),
               br(),
               
               textOutput("userguess_dummy")),
  
  mainPanel(
    plotOutput("regPlot_dummy"))))
```


```{r, context="server"}

output$userguess_dummy <- renderText({

  a <- input$i_dummy
  b <- input$s_dummy
  paste0("Your guess:\n y = ", a, " + ", b, "x")
  
})

output$regPlot_dummy <- renderPlot({
 
  set.seed(19)
  
  # Generate Random Data
  dta <- data.frame(x = sample(x = c(0, 1), size = 20, replace = T),
                    y = rnorm(n = 20, mean = 2, sd = 1))
  dta[dta$x == 1, "y"] <- dta[dta$x == 1, "y"] + 3
  
  x <- dta[, "x"]
  y <- dta[, "y"]
  #y = 2 + 3*x + u
      
      
  # a = intercept, b = slope (user input)
  a <- input$i_dummy
  b <- input$s_dummy
      
  # plot
  expr <- function(x) a + b*x
  errors <- (a + b*x) - y
  
  plot(x, y, type = "p", pch = 21, col = "blue", bg = "royalblue", asp=.25,
       xlim = c(-.1, 1.1),
       ylim = c(min(y)-.1, max(y)+.1),
       main = "Fit the data!", frame.plot = T,
       cex = 1.2)
  if (input$meany_x0 == T){
    points(0, mean(dta[dta$x == 0, "y"]), col = 'orange',
           cex = 3, pch = 15)
    text(0.05, mean(dta[dta$x == 0, "y"]), "E[Y | X = 0]", pos = 4)
  }
  if (input$meany_x1 == T){
    points(1, mean(dta[dta$x == 1, "y"]), col = 'orange',
           cex = 3, pch = 15)
    text(1.05, mean(dta[dta$x == 1, "y"]), "E[Y | X = 1]", pos = 4)
  }
  
  
  
  b_true = cov(x, y)/var(x)
  a_true = mean(y) - b_true*mean(x)
  
  if (near(a, a_true, tol = .125) && near(b, b_true, tol = .125)){
    curve(expr = expr, from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "green")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 0, green = 1, blue = 0, alpha = 0.05), border = NA)
  } else {
    curve(expr =expr , from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "red")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 1, green = 0, blue = 0, alpha = 0.05), border = NA)
  }

})
```


## Standardized Regression

```{r, echo=FALSE}
shinyUI(fluidPage(
  sidebarPanel(sliderInput("i_std", "Intercept", min = -2,
                           max = 2, step = .5, value = .5),
               sliderInput("s_std", "Slope", min = -2,
                           max = 2, step = .1, value = .1),
               
               checkboxInput("std", "Standardize X and Y!", value = F),
               
               br(),
               br(),
               
               textOutput("userguess_std")),
  
  mainPanel(
    plotOutput("regPlot_std"))))
```


```{r, context="server"}

output$userguess_std <- renderText({

  if (input$std == F){
    a <- input$i_std
    b <- input$s_std
    paste0("Your guess:\n y = ", a, " + ", b, "x")
  } else {
    a <- input$i_std
    b <- input$s_std
    paste0("Your guess:\n [y / SD(y)] = ", a, " + ", b, "[x / SD(x)]")
  }

  
})

output$regPlot_std <- renderPlot({
 
  set.seed(19)
  
  # Generate Random Data
  x <- rnorm(n = 20, mean = 2, sd = 4)

  a_true <- -2
  b_true <- 1.5
  y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = 3)
  # True DGP: y = -2 + 1.5 * x + u
  
  if (input$std == T){
    x <- x/sd(x)
    y <- y/sd(y)
  }
  
      
      
  # a = intercept, b = slope (user input)
  a <- input$i_std
  b <- input$s_std
      
  # plot
  expr <- function(x) a + b*x
  errors <- (a + b*x) - y 
  
  plot(x, y, type = "p", pch = 21, col = "blue", bg = "royalblue", asp=1,
       xlim = c(-15, 15),
       ylim = c(-10, 10),
       main = "Fit the data!", frame.plot = FALSE,
       cex = 1.2)
  legend("topleft", legend = paste0("r (correlation coefficient) = ", round(cor(x, y), 3)))
  
  b_best <- cov(x, y)/var(x)
  a_best <- mean(y) - b_best*mean(x)
  
  if (near(a, a_best, tol = .25) && near(b, b_best, tol = .05)){
    curve(expr = expr, from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "green")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 0, green = 1, blue = 0, alpha = 0.05), border = NA)
  } else {
    curve(expr =expr , from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "red")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 1, green = 0, blue = 0, alpha = 0.05), border = NA)
  }

})
```

