---
title: "Reg_SSR_Plotly_standalone"
runtime: shiny_prerendered
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(plotly)
library(viridisLite)
```

```{r, echo=FALSE}
shinyUI(fluidRow(
  
  column(width = 2,
         sliderInput("i_ssr", "Intercept", min = -4,
                           max = 4, step = .25, value = .5),
         sliderInput("s_ssr", "Slope", min = -4,
                           max = 4, step = .25, value = -1),
         br(),
         br(),
               
         textOutput("userguess_ssr")),
  
  column(width = 4,
         plotOutput("regPlot_ssr")),
  
  column(width = 6,
         plotlyOutput("SSR_cone"))
  
))
```


```{r, context="server"}

output$userguess_ssr <- renderText({

  a <- input$i_simple
  b <- input$s_simple
  paste0("Your guess:\n y = ", a, " + ", b, "x")
  
})

output$regPlot_ssr <- renderPlot({
 
  set.seed(19)
  
  # Generate Random Data
  x <- rnorm(n = 20, mean = 2, sd = 4)
  
  a_true <- -2
  b_true <- 1.5
  y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = 1.5)
  # True DGP: y = -2 + 1.5 * x + u
      
  # a = intercept, b = slope (user input)
  a <- input$i_ssr
  b <- input$s_ssr
      
  # plot
  expr <- function(x) a + b*x
  errors <- (a + b*x) - y 
  
  plot(x, y, type = "p", pch = 21, col = "blue", bg = "royalblue", asp=1,
       xlim = c(min(c(x, y))-1, max(c(x, y))+1),
       ylim = c(min(c(x, y))-1, max(c(x, y))+1),
       main = "Fit the data!", frame.plot = FALSE,
       cex = 1.2)
  
  b_best = cov(x, y)/var(x) #approx. 1.25
  a_best = mean(y) - b_best*mean(x) #approx -1
  
  if (near(a, a_best, tol = .125) &&  near(b, b_best, tol = .125)){
    curve(expr = expr, from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "green")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 0, green = 1, blue = 0, alpha = 0.05), border = NA)
  } else {
    curve(expr =expr , from = min(x)-10, to = max(x)+10, add = TRUE, col = "black")
    segments(x0 = x, y0 = y, x1 = x, y1 = (y + errors), col = "red")
    rect(xleft = x, ybottom = y,
         xright = x + abs(errors), ytop = y + errors, density = -1,
         col = rgb(red = 1, green = 0, blue = 0, alpha = 0.05), border = NA)
  }

})

output$SSR_cone <- renderPlotly({
  set.seed(19)
  
  # Generate Random Data
  x <- rnorm(n = 20, mean = 2, sd = 4)
  
  a_true <- -2
  b_true <- 1.5
  y <- a_true + b_true*x + rnorm(n = 20, mean = 0, sd = 1.5)
  # True DGP: y = -2 + 1.5 * x + u
      
  # a = intercept, b = slope (user input)
  a <- input$i_ssr
  b <- input$s_ssr
      
  # plot cone

  ssr <- function(a_, b_){
    return(sum(((a_ + b_*x) - y)^2))
  }
  
  possible_a <- seq(-4, 4, .25)
  possible_b <- seq(-4, 4, .25)
  
  df <- data.frame(a = rep(possible_a, each = length(possible_b)),
                   b = rep(possible_b, times = length(possible_b)))
  
  df <- cbind(df, mapply(ssr, df$a, df$b))
  colnames(df) <- c("a", "b", "ssr")
  #df$ssr <- log(df$ssr) #uncomment for log
  
  annot <- data.frame(a_ = a, b_ = b, ssr_ = log(ssr(a, b)))
  #annot <- data.frame(a_ = a, b_ = b, ssr_ = log(ssr(a, b))) uncomment for log
 
  plot_ly(df, x = ~a, y = ~b, z = ~ssr)  %>%
  add_markers(color = ~ssr, name = "SSR",
              colors = viridis(10, option = "A"), opacity = .75) %>%
  colorbar(title = "Sum of Squared\nResiduals") %>%
  add_markers(x = ~a_, y = ~b_, z = ~ssr_, data = annot, name = "Your Guess") %>%
  layout(title = "Sum of Squared Residuals\n(Surface Plot, your guess shown in green)",
         xaxis=list(range=c(-6,6)), yaxis=list(range=c(-6,6))) 
  # Not sure how to change default zoom...
  


  
  
  
})

```

