app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(scale_x = 0.5)
app$setInputs(scale_x = -0.5)
app$setInputs(scale_x = -3)
app$setInputs(scale_x = -4)
app$setInputs(scale_x = -0.5)
app$setInputs(scale_x = 1.5)
app$setInputs(scale_x = 3.5)
app$setInputs(scale_x = 5)
app$setInputs(scale_y = -3.5)
app$setInputs(scale_y = -1.5)
app$setInputs(scale_y = 2.5)
app$setInputs(scale_x = -1.5)
app$snapshot()
