app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(scale_y = 1.5)
app$setInputs(scale_y = 2)
app$setInputs(scale_y = 0)
app$setInputs(scale_y = -0.5)
app$setInputs(scale_y = 1)
app$setInputs(scale_x = 1.5)
app$setInputs(scale_x = 2)
app$setInputs(scale_x = -1)
app$setInputs(scale_x = -1.5)
app$setInputs(scale_x = -2)
app$setInputs(scale_x = 0.5)
app$setInputs(scale_x = 1)
app$snapshot()
