app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(s_dummy = 0.75)
app$setInputs(i_dummy = 4)
app$setInputs(s_dummy = 3)
app$setInputs(i_dummy = 1.75)
app$setInputs(meany = TRUE)
app$setInputs(meany_x1 = TRUE)
app$setInputs(meany_x0 = TRUE)
app$snapshot()
