app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(i_dummy = 1.75)
app$setInputs(s_dummy = 3.25)
app$setInputs(i_dummy = 0.5)
app$setInputs(s_dummy = 2.5)
app$setInputs(i_dummy = 3.75)
app$setInputs(meany = TRUE)
app$setInputs(meany = FALSE)
app$setInputs(meany_x0 = TRUE)
app$setInputs(meany_x0 = FALSE)
app$setInputs(meany_x1 = TRUE)
app$setInputs(meany_x0 = TRUE)
app$setInputs(meany = TRUE)
app$setInputs(s_dummy = 1.5)
app$setInputs(i_dummy = 3.25)
app$setInputs(s_dummy = 3.25)
app$setInputs(s_dummy = 3.5)
app$setInputs(s_dummy = 3.75)
app$setInputs(i_dummy = 2)
app$snapshot()
app$setInputs(meany = FALSE)
app$setInputs(meany_x0 = FALSE)
app$snapshot()
app$setInputs(s_dummy = 0.5)
app$snapshot()
app$setInputs(i_dummy = 3.5)
app$setInputs(meany_x1 = FALSE)
app$snapshot()
