app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(s_dummy = 1)
app$setInputs(i_dummy = 2)
app$setInputs(i_dummy = 3.25)
app$setInputs(s_dummy = 2.25)
app$setInputs(i_dummy = 1)
app$setInputs(i_dummy = 2)
app$setInputs(meany = TRUE)
app$setInputs(meany_x0 = TRUE)
app$setInputs(meany_x1 = TRUE)
app$setInputs(s_dummy = 2.5)
app$setInputs(s_dummy = 3)
app$setInputs(i_dummy = 2.25)
app$snapshot()
