app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(ssize = 43)
app$setInputs(ssize = 113)
app$setInputs(ssize = 183)
app$setInputs(ssize = 250)
app$setInputs(ssize = 111)
app$setInputs(ssize = 44)
app$snapshot()
