app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(new = "click")
app$setInputs(new = "click")
app$setInputs(new = "click")
app$setInputs(new = "click")
app$setInputs(new = "click")
app$setInputs(new = "click")
app$setInputs(new = "click")
app$setInputs(new = "click")
