app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(addr = "1")
app$setInputs(addr = c("1", "2"))
app$setInputs(addr = c("1", "2", "3"))
app$setInputs(addr = c("1", "2", "3", "4"))
app$setInputs(addr = c("1", "2", "4"))
app$setInputs(addr = c("1", "4"))
app$setInputs(addr = "4")
app$setInputs(addr = character(0))
app$setInputs(addr = "3")
app$snapshot()
app$setInputs(addr = c("3", "4"))
app$snapshot()
app$setInputs(addr = c("1", "3", "4"))
app$snapshot()
app$setInputs(addr = c("1", "4"))
app$setInputs(addr = "1")
app$snapshot()
