app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(s_dm = -0.5)
app$setInputs(i_dm = 1)
app$setInputs(i_dm = 1.5)
app$snapshot()
app$setInputs(s_dm = 0.8)
app$setInputs(s_dm = 1.2)
app$setInputs(i_dm = -0.5)
app$snapshot()
