app <- ShinyDriver$new("../", seed = 1)
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(i_dm = 1)
app$setInputs(i_dm = 2.5)
app$setInputs(i_dm = 0.5)
app$setInputs(i_dm = 1.5)
app$setInputs(i_dm = 2)
app$setInputs(s_dm = -1.1)
app$setInputs(s_dm = 1.1)
app$setInputs(s_dm = 1.2)
app$snapshot()
app$setInputs(dm = TRUE)
app$setInputs(i_dm = -0.5)
app$setInputs(i_dm = 0)
app$snapshot()
