app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(i_dm = 1)
app$setInputs(s_dm = 1.1)
app$setInputs(s_dm = 1.3)
app$setInputs(s_dm = 1.2)
app$setInputs(i_dm = 1.5)
app$setInputs(dm = TRUE)
app$setInputs(i_dm = 1)
app$setInputs(i_dm = 0)
app$snapshot()
