app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(s_simple = 0.7)
app$setInputs(i_simple = -0.1)
app$setInputs(s_simple = 0.9)
app$setInputs(i_simple = 1.2)
app$setInputs(i_simple = 1)
app$setInputs(i_simple = 0.9)
app$setInputs(i_simple = 1)
app$setInputs(i_simple = 1.1)
app$setInputs(i_simple = 1.2)
app$setInputs(s_simple = 0.8)
app$setInputs(s_simple = 1.4)
app$setInputs(s_simple = 1.1)
app$setInputs(s_simple = 1)
