app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(i_simple = 0.9)
app$setInputs(i_simple = -1.2)
app$setInputs(s_simple = 0)
app$snapshot()
app$setInputs(s_simple = 0.7)
app$setInputs(s_simple = 1)
app$setInputs(i_simple = -1.5)
app$setInputs(i_simple = -2)
app$setInputs(s_simple = 1.4)
app$setInputs(s_simple = 1.5)
app$snapshot()
